### ISSUE TITLE
Html generation tests for Plotly.NET: plan

### ISSUE THREAD

**Issue by WhiteBlackGoose** [plotly/Plotly.NET#104]
The following groups of tests are taken from https://plotly.net/:

- [x] Chart layout
- [x] Simple charts
- [x] 3D charts
- [x] Distribution charts
- [x] Geo map charts
- [x] Mapbox map charts
- [x] Finance charts
- [x] Polar charts
- [x] Categorical charts

Please, assign it to me

**Comment by kMutagene** [comment]
Thank you very much for all those tests!
