### ISSUE TITLE
Sliders

### ISSUE THREAD

**Issue by kMutagene** [plotly/Plotly.NET#120]

**Comment by amakhno** [comment]
@kMutagene 

Hi!

Can I try to implement it at the weekend? We need this functionality in the project, and I want to know if it's being implemented by someone right now

**Comment by kMutagene** [comment]
Hi @amakhno ,

To my knowledge, this is not currently worked on, so feel free to have a go!

All properties of the Slider object can be found [here](https://plotly.com/javascript/reference/layout/sliders/) alongside the correct property names

The pattern we use for layout objects can be for example seen here: https://github.com/plotly/Plotly.NET/blob/dev/src/Plotly.NET/Layout/ObjectAbstractions/Common/Annotation.fs

as you see, it is basically just the task of copy pasting the props and names and assigning correct .NET types. A few hints on that (it may be possible that you do not need this though):
- nested objects need their own abstractions, for example the font (check if they are implemented already, `Font` does exist for example.)
- `data array` should be `seq<#IConvertible>`
- `number` should be an int (for example for pixels) or float (for example for fractions) depending on context of the reference docs
- things that can be a single value or an array of values on the JS side should use the single or multi pattern you can see for example [here](https://github.com/plotly/Plotly.NET/blob/e97340cad5b627133fd16d9f4cf57b70619edf55/src/Plotly.NET/Traces/Trace2D.fs#L211-L212)

And a function for adding such an object to the layout [here for F#](https://github.com/plotly/Plotly.NET/blob/e97340cad5b627133fd16d9f4cf57b70619edf55/src/Plotly.NET/ChartAPI/Chart.fs#L869), and [here for the C# extension](https://github.com/plotly/Plotly.NET/blob/e97340cad5b627133fd16d9f4cf57b70619edf55/src/Plotly.NET/CSharpLayer/GenericChartExtensions.fs#L547).

If you have additional questions feel free to ask here or in the fslab discord channel!

**Comment by kMutagene** [comment]
closed via #232
