### ISSUE TITLE
DUs and types to be named consistently with F# style

### ISSUE THREAD

**Issue by WhiteBlackGoose** [plotly/Plotly.NET#121]
Similar to #105 we also want to make naming of internal types (like `FontFamily` and `Fill`) to be PascalCase.

**Comment by kMutagene** [comment]
Same is true for parameter names (e.g. `Showline` -> `ShowLine`)

**Comment by kMutagene** [comment]
I have not looked at every single of the thousands of positions where this applies, but it is definitely the norm to do it like this now.
