### ISSUE TITLE
failed to reproduce bubble-scatter-plots example from plotly python

### ISSUE THREAD

**Issue by aammfe** [plotly/Plotly.NET#124]
### Description
I'm using .Net interactive notebooks(v1.0.2409020) in Visual studio code and trying to reproduce [bubble-scatter-plots](https://plotly.com/python/line-and-scatter/#bubble-scatter-plots) but colors are not not being applied on bubbles.  

This is code
```
### Repro steps
#r "nuget: Plotly.NET, 2.0.0-preview.6"
#r "nuget: Plotly.NET.Interactive, 2.0.0-preview.6"
open Plotly.NET

let xs =[1; 2; 3; 4]
let ys =[10;11; 12; 13]

Chart.Scatter(xs, ys, StyleParam.Mode.Markers, Name="Markers")
        |> Chart.withMarker(Marker.init(MultiSizes=[40; 60; 80; 100], Colors = ["#4287f5";"#cb23fa";"#23fabd";"#ff7b00"]))
```

### Expected behavior
This is Example From plotly python here colors are working fine.
![image](https://user-images.githubusercontent.com/11896817/129242944-4c234452-5fc6-4edc-bf1b-0d1c3556695d.png)

### Actual behavior
But here colors are not working 
![image](https://user-images.githubusercontent.com/11896817/129243199-7a2190d7-ae55-496a-923b-963c7524235c.png)

Colors should be apply on each Bubble

**Comment by kMutagene** [comment]
Colors the way plotly.js are using them are quite difficult to handle in F#, as it can be a single color or an array. For now the easiest way to get around this when using color arrays is setting the color property manually on the Marker used in the charts:

```fsharp
#r "nuget: Plotly.NET, 2.0.0-preview.6"
open Plotly.NET

let xs =[1; 2; 3; 4]
let ys =[10;11; 12; 13]

Chart.Scatter(xs, ys, StyleParam.Mode.Markers, Name="Markers")
|> Chart.withMarker(
    let m = Marker.init(MultiSizes=[40; 60; 80; 100])
    m?color <- ["#4287f5";"#cb23fa";"#23fabd";"#ff7b00"]
    m
)
|> Chart.Show
```
![image](https://user-images.githubusercontent.com/21338071/129317148-186832a3-c3bd-42c0-a35f-120c47ca75b1.png)


(btw, `Colors` not working is a real bug. the property gets set to `colors` instead of `color`)

**Comment by aammfe** [comment]
> Colors the way plotly.js are using them are quite difficult to handle in F#, as it can be a single color or an array.

why we don't use Discriminated union ?

`type Color = Color string | Color [IConvertable<a>]`
I'm sure code is wrong but you got the idea.

**Comment by kMutagene** [comment]
Color is so central that we would like it to be easily used from C# as well. But yes, a DU would solve this on the F# side and might be the solution we go for eventually if we do not find something better.
