### ISSUE TITLE
Marker.init Colors not having effect

### ISSUE THREAD

**Issue by gaviei** [plotly/Plotly.NET#138]
The example "Customizing Individual Bar Colors" in https://plotly.com/python/bar-charts/#customizing-individual-bar-colors requires the assignment of multiple colors in a markers, which is available in the init method, but has no effect:

```
#r "nuget: Plotly.NET, 2.0.0-preview.6"
#r "nuget: Plotly.NET.Interactive, 2.0.0-preview.6"

let featureKeys = ["Feature A"; "Feature B"; "Feature C";
                   "Feature D"; "Feature E"]
let featureValues = [20; 14; 23; 25; 22]

let colors = 
    [1..5]
    |> List.mapi (fun i x -> if i = 1 then "crimson" else "lightslategray" )
    |> List.toSeq

let marker = Marker.init(Colors = colors);
// marker?color<-colors

Chart.Column (featureKeys, featureValues, Marker=marker)
```
![image](https://user-images.githubusercontent.com/7762947/130689575-c8b6c222-ce30-4080-aee9-5f411288993f.png)

in the other hand, the dynamic assignment of color works:
![image](https://user-images.githubusercontent.com/7762947/130689678-5adb2988-70fb-4621-ae27-54b40ed8ef68.png)

**Comment by kMutagene** [comment]
@gaviei can you please add the code directly here instead of a screenshot so i can copy paste it to test? also for the other issues

**Comment by gaviei** [comment]
@kMutagene Issue comment was updated. Please check and let me know.
