### ISSUE TITLE
Chart.Column "width" abstraction missing

### ISSUE THREAD

**Issue by gaviei** [plotly/Plotly.NET#139]
The example "Customizing Individual Bar Widths" in https://plotly.com/python/bar-charts/#customizing-individual-bar-widths requires the assignment of the property "width" which is missing in the abstraction:

![](https://user-images.githubusercontent.com/7762947/130377416-d63fabb0-b95a-47de-bf32-c81ceaa9ef65.png)

**Comment by kMutagene** [comment]
please move to #137
