### ISSUE TITLE
Chart.Column "base" abstraction missing

### ISSUE THREAD

**Issue by gaviei** [plotly/Plotly.NET#140]
The example "Customizing Individual Bar Base" in https://plotly.com/python/bar-charts/#customizing-individual-bar-base requires the assignment of the property "base" which is missing in the abstraction:

![](https://user-images.githubusercontent.com/7762947/130377845-1c6fac7b-f97a-4baf-a0b9-94e01bbcd910.png)

**Comment by kMutagene** [comment]
please move to #137
