### ISSUE TITLE
Drawing Shapes on Cartesian Plots

### ISSUE THREAD

**Issue by MaheshPunna** [plotly/Plotly.NET#165]
Ability to draw shapes (Rectangle/Circle) "by mouse" and styling of user-drawn shapes

Reference: https://plotly.com/r/shapes/

**Comment by kMutagene** [comment]
Please also look at our documentation in addition to exploring the API. We have a page on exactly that: https://plotly.net/1_3_shapes.html

**Comment by MaheshPunna** [comment]
I actually meant the ability to draw shapes by mouse

**Comment by kMutagene** [comment]
Ah i see, thats only possible with dynamic object at the moment. Ill add extensions to `StyleParam.DragMode` for that. When it is live, you can do it like this:

```fsharp
Chart.Invisible() 
|> Chart.withLayout(
    Layout.init(
        DragMode = StyleParam.DragMode.DrawRect
    )
)
|> Chart.show
```

![image](https://user-images.githubusercontent.com/21338071/131799738-ebaaa44a-0f4c-4e74-9850-e3dfd67f27b0.png)

**Comment by kMutagene** [comment]
The next version also will add mode bar buttons:

```fsharp

Chart.Invisible() 
|> Chart.withLayout(
    Layout.init(
        DragMode = StyleParam.DragMode.DrawRect
    )
)
|> Chart.withConfig(
    Config.init(
        ModeBarButtonsToAdd = [
            StyleParam.ModeBarButton.DrawLine
            StyleParam.ModeBarButton.DrawOpenPath
            StyleParam.ModeBarButton.DrawClosedPath
            StyleParam.ModeBarButton.DrawCircle
            StyleParam.ModeBarButton.DrawRect
            StyleParam.ModeBarButton.EraseShape

        ]
    )
)
|> Chart.show
```
![image](https://user-images.githubusercontent.com/21338071/131804641-b8b5baf0-a1ca-42e7-a369-fbb573ded187.png)
