### ISSUE TITLE
Broken Log axis

### ISSUE THREAD

**Issue by pkese** [plotly/Plotly.NET#172]
As of `preview.7` the Log axes don't work.

See the chart at documentation page:  
https://plotly.net/1_0_axis-styling.html#f6bf5bd2-ce5e-43f6-a283-fbbd1910d7a1  
(y axis should be logarithmic, but is linear)

**Comment by pkese** [comment]
Or search for `AxisType = StyleParam.AxisType.Log` if the link above doesn't work.

**Comment by pkese** [comment]
Btw, it worked with `preview.6`.

**Comment by kMutagene** [comment]
@pkese good catch thanks! the new update accidentally sets `axistype` instead of `type` on the axis, which will not work. So if you want to use preview.7 here is a workaround until a new version is out incorporating the fix:

```fsharp
let myAxis = LinearAxis.init(...) //create your axis as before
myAxis?("type") <- "log"
```
