### ISSUE TITLE
Plot Issue for Mapbox Choropleth Map Using GeoJSON 

### ISSUE THREAD

**Issue by MaheshPunna** [plotly/Plotly.NET#177]
```
open Plotly.NET
open Newtonsoft.Json

let geoJson = 
    Http.RequestString "https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json"
    |> JsonConvert.DeserializeObject 

type csvProvider = CsvProvider<"https://raw.githubusercontent.com/plotly/datasets/master/fips-unemp-16.csv">

let fips_data = csvProvider.Load("https://raw.githubusercontent.com/plotly/datasets/master/fips-unemp-16.csv")

let z = fips_data.Rows |> Seq.map (fun row -> float row.Unemp)
let locations = fips_data.Rows |> Seq.map (fun row -> row.Fips)

Chart.ChoroplethMapbox(z=z,geoJson=geoJson,locations=locations,FeatureIdKey="id",Colorscale=StyleParam.Colorscale.Viridis,ZMin=0.,ZMax=12.)
|> Chart.withMapbox(
        Mapbox.init(Style=StyleParam.MapboxStyle.CartoPositron,Zoom=3.,Center=(-95.7129,37.0902)) 
    )
|> Chart.withSize(width=1100.,height=700.)
```

Expected Plot:

![image](https://user-images.githubusercontent.com/7539514/132092808-6d79254d-97df-4484-8d1a-c03a04ed7675.png)

Current Plot:
![image](https://user-images.githubusercontent.com/7539514/132092838-391b6572-8f1d-4290-a9e1-566d3c160821.png)

**Comment by kMutagene** [comment]
The exact same data is used in our docs: https://plotly.net/6_2_choropleth-mapbox.html, so it looks more like an issue of your way of accessing the data to me.

![image](https://user-images.githubusercontent.com/21338071/132119734-f97760d0-25de-466b-818b-9003275a0451.png)

**Comment by kMutagene** [comment]
@MaheshPunna have you tried this using the code from the docs?

**Comment by MaheshPunna** [comment]
@kMutagene Yes, you are right. There seems to be some problem in json type provider. Fixed now. Thanks
