### ISSUE TITLE
Plotting images

### ISSUE THREAD

**Issue by oluwandabira** [plotly/Plotly.NET#185]
Similar to plotly's python [imshow](https://plotly.com/python/imshow/).

I understand that there is no almost universal tensor library in .NET like numpy but it would be nice to be able to plot and compose plots of images within .NET especially with the notebooks.

**Comment by kMutagene** [comment]
Hi @oluwandabira, the image plot is one of the few missing trace types left to implement for Plotly.NET. You can take a look at the status of API coverage [here](https://github.com/plotly/Plotly.NET/issues/42). Its on the list and will be available soon.

For actual manipulation of the image after this trace is implemented, i would suggest a library such as https://github.com/SixLabors/ImageSharp

**Comment by oluwandabira** [comment]
Is there a timeline for when it would be available or is someone working on it already? I don't see an open pr for this and if no one is working on it yet I could try to contribute an implementation.

**Comment by kMutagene** [comment]
The trace does not have many parameters, so it's an easy one. I will implement it today, unless you are interested in contributing, then ill leave it to you 😉
