### ISSUE TITLE
"X Unified" for HoverMode in Line Chart

### ISSUE THREAD

**Issue by MaheshPunna** [plotly/Plotly.NET#214]
There is no abstraction available to set "X Unified" for HoverMode in Line Charts

![image](https://user-images.githubusercontent.com/7539514/135701993-10fedcee-2d22-4d3f-878c-fdc09ec8e5de.png)

**Comment by kMutagene** [comment]
Fixed via https://github.com/plotly/Plotly.NET/commit/2aef8606852a4bc0225e49c7927a209f0219609c
