### ISSUE TITLE
Chart axes switched

### ISSUE THREAD

**Issue by luisquintanilla** [plotly/Plotly.NET#218]
Am I interpreting the Column & Bar Chart example wrong or is the sample wrong? Looks to me like the product should be on the x-axis and the values on the y-axis.

## Current sample

https://plotly.net/02_1_bar-and-column-charts.html

![image](https://user-images.githubusercontent.com/46974588/136583307-60230d37-ff95-4dc0-a271-2aeaa60e589f.png)

## Expected?

![image](https://user-images.githubusercontent.com/46974588/136584641-8cab47a2-7f0f-4810-b74e-28907fa09b6f.png)

**Comment by luisquintanilla** [comment]
@kMutagene I created a PR for this. Feel free to close if I'm interpreting wrong. Thanks!

**Comment by kMutagene** [comment]
@luisquintanilla you are absolutely right, i forgot to switch this after adapting the function to take keys as optional argument, thanks!
