### ISSUE TITLE
Sum in PointTernary Plot is not working as expected

### ISSUE THREAD

**Issue by MaheshPunna** [plotly/Plotly.NET#226]
```
open Plotly.NET

// a coordinates
let a  = [ 10; 20; 30;]
// b coordinates
let b  = [ 10; 20; 30;]
//c
let c  = [ 80; 60; 40;]

Chart.PointTernary(a,b,c,Sum=100.)
```

Current behavior:
![image](https://user-images.githubusercontent.com/7539514/138384706-cd7dc791-02b0-4522-a31d-a91078a7a731.png)

**Comment by kMutagene** [comment]
Sum is working as expected - your example uses values for all three axes, which is why sum is not used - sum will only work when one value is missing, and add up to it.
