### ISSUE TITLE
Abstraction missing for setting xaxis_range for Date time series data

### ISSUE THREAD

**Issue by MaheshPunna** [plotly/Plotly.NET#227]
LinearAxis provides Range Property for setting Axis Range that accepts only float values, How can I pass date strings as range values for axis Or Any workaround?

**Comment by kMutagene** [comment]
Fixed via https://github.com/plotly/Plotly.NET/commit/d13c047f79768c444692f9a44ff7e1c368d61b7a (using IConvertible tuple for ranges)
