### ISSUE TITLE
Custom Candlestick Colors does not seem to be working

### ISSUE THREAD

**Issue by MaheshPunna** [plotly/Plotly.NET#229]
```
Chart.Candlestick(
    stockData,
    Increasing = Line.init (Color = Color.fromString "cyan"),
    Decreasing = Line.init (Color = Color.fromString "gray")
)
```
The same behavior is observed for Chart.OHLC 

Current Behavior:
![image](https://user-images.githubusercontent.com/7539514/138585929-22bd13f1-a292-4098-821e-4b75984d01b1.png)

Expected Behavior:
![image](https://user-images.githubusercontent.com/7539514/138585962-d6eefe86-ff81-41f3-8ace-bc292b0a4a64.png)

**Comment by neilyoung2008** [comment]
`var candle_Chart = Chart2D.Chart.Candlestick<int, int, int, int, DateTime, string>
                                (
                                    open : open, 
                                    high : high, 
                                    low  : low, 
                                    close: close, 
                                    X : date, 
                                    Name: "K", 
                                    IncreasingColor : upcolor,
                                    DecreasingColor : dncolor,
                                    //Increasing :FinanceMarker.init(MarkerColor:Color.fromString("black"), LineColor:upcolor, LineWidth:1, LineDash :StyleParam.DrawingStyle.Solid), 
                                    //Decreasing :FinanceMarker.init(MarkerColor:dncolor, LineColor:dncolor, LineWidth:1, LineDash :StyleParam.DrawingStyle.Solid), 
                                    ShowLegend : false,    
                                    Line : Line.init
                                                    (
                                                        //Colorscale:colorscale,  
                                                        //Color : Color.fromColorScaleValues<double>(zd_colors),
                                                        Width : 0.5
                                                    ),                                

                                                    UseDefaults : false
                                );`

**Comment by neilyoung2008** [comment]
var candle_Chart = Chart2D.Chart.Candlestick<int, int, int, int, DateTime, string>
                                (
                                    open : open, 
                                    high : high, 
                                    low  : low, 
                                    close: close, 
                                    X : date, 
                                    Name: "K", 
                                    IncreasingColor : upcolor,
                                    DecreasingColor : dncolor,
                                    //Increasing :FinanceMarker.init(MarkerColor:Color.fromString("black"), LineColor:upcolor, LineWidth:1, LineDash :StyleParam.DrawingStyle.Solid), 
                                    //Decreasing :FinanceMarker.init(MarkerColor:dncolor, LineColor:dncolor, LineWidth:1, LineDash :StyleParam.DrawingStyle.Solid), 
                                    ShowLegend : false,    
                                    Line : Line.init
                                                    (
                                                        //Colorscale:colorscale,  
                                                        //Color : Color.fromColorScaleValues<double>(zd_colors),
                                                        Width : 0.5
                                                    ),                                

                                                    UseDefaults : false
                                );
                                    high : high, 
                                    low  : low, 
                                    close: close, 
                                    X : date, 
                                    Name: "K", 
                                    IncreasingColor : upcolor,
                                    DecreasingColor : dncolor,
                                    //Increasing :FinanceMarker.init(MarkerColor:Color.fromString("black"), LineColor:upcolor, LineWidth:1, LineDash :StyleParam.DrawingStyle.Solid), 
                                    //Decreasing :FinanceMarker.init(MarkerColor:dncolor, LineColor:dncolor, LineWidth:1, LineDash :StyleParam.DrawingStyle.Solid), 
                                    ShowLegend : false,    
                                    Line : Line.init
                                                    (
                                                        //Colorscale:colorscale,  
                                                        //Color : Color.fromColorScaleValues<double>(zd_colors),
                                                        Width : 0.5
                                                    ),                                

                                                    UseDefaults : false
                                );`

**Comment by neilyoung2008** [comment]
var candle_Chart = Chart2D.Chart.Candlestick<int, int, int, int, DateTime, string>
                                (
                                    open : open, 
                                    high : high, 
                                    low  : low, 
                                    close: close, 
                                    X : date, 
                                    Name: "K", 
                                    IncreasingColor : upcolor,
                                    DecreasingColor : dncolor,
                                    //Increasing :FinanceMarker.init(MarkerColor:Color.fromString("black"), LineColor:upcolor, LineWidth:1, LineDash :StyleParam.DrawingStyle.Solid), 
                                    //Decreasing :FinanceMarker.init(MarkerColor:dncolor, LineColor:dncolor, LineWidth:1, LineDash :StyleParam.DrawingStyle.Solid), 
                                    ShowLegend : false,    
                                    Line : Line.init
                                                    (
                                                        //Colorscale:colorscale,  
                                                        //Color : Color.fromColorScaleValues<double>(zd_colors),
                                                        Width : 0.5
                                                    ),                                

                                                    UseDefaults : false
                                );

**Comment by neilyoung2008** [comment]
//Increasing :FinanceMarker.init(MarkerColor:Color.fromString("black"), LineColor:upcolor, LineWidth:1, LineDash :StyleParam.DrawingStyle.Solid),
//Decreasing :FinanceMarker.init(MarkerColor:dncolor, LineColor:dncolor, LineWidth:1, LineDash :StyleParam.DrawingStyle.Solid),

The param ： Increasing /Decreasing  isnot work.

**Comment by neilyoung2008** [comment]
@kMutagene

**Comment by kMutagene** [comment]
@neilyoung2008 please open a new issue with a well formatted reproducible code example, as well as information about the version, language, and os you are using.
