### ISSUE TITLE
New .NET Interactive assemblies up on nuget

### ISSUE THREAD

**Issue by dsyme** [plotly/Plotly.NET#236]
There are new .NET Interactive assemblies up on nuget.org, it would be good to update Plotly.NET to match

https://github.com/dotnet/interactive/issues/1719

**Comment by kMutagene** [comment]
@dsyme which version of .NET interactive and Plotly.NET.Interactive are you using? It works fine for me on 

`ms-dotnettools.dotnet-interactive-vscode @ v1.0.2559020`  with `Plotly.NET.Interactive @ 2.0.0-preview.12` :

![image](https://user-images.githubusercontent.com/21338071/141122475-1b281228-5e7e-4e0d-a758-bb820e7dc064.png)

**Comment by kMutagene** [comment]
Anyways, i updated the dependencies to dotnet interactive again with `2.0.0-preview.14`, can you check if everything is in order for you now?
