### ISSUE TITLE
.NET Interactive dosen't provide Newtonsoft.Json

### ISSUE THREAD

**Issue by colombod** [plotly/Plotly.NET#242]
### Description

.NET Interactive is moving to .NET 6.0 and dropping depednency on Newtonsoft.Json

### Repro steps

use VSCode Insider and lastest .NET Interactive

1. load Plotly.NET and Plotly.NET.Interactive

2. Display simple chart

### Expected behavior

The char is rendered 

### Actual behavior

File not found exception for Newtonsoft.Json 13.0.0

### Known workarounds

Please provide a description of any known workarounds.

### Related information 

* Operating system
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by kMutagene** [comment]
Not sure if i understand this correctly, but Newtonsoft.Json is a dependency of Plotly.NET, why is it not resolved in a notebook like other deps? Does it have to be an explicit dependency of Plotly.NET.Interactive as well (currently it is just transitive via the dependency to Plotly.NET)?

**Comment by colombod** [comment]
It seems to fail to resolve the dependency I have open an issue in .NET interactive for that

**Comment by colombod** [comment]
https://github.com/dotnet/interactive/issues/1770
