### ISSUE TITLE
Some AngularAxis's Layout Styles mapped incorrectly 

### ISSUE THREAD

**Issue by FlippievanDyk** [plotly/Plotly.NET#251]
### Description

Certain Layout style  are incorrectly mapped to their correct JSON representation. 

I have specifically noticed that AngularAxis's Direction and Rotation values are not mapped correctly. There may be others, these are the one's that I noticed/require for my project.

using 

### Repro steps

using 2.0.0-preview.16, with example code as starting point:

```F#
open Plotly.NET
open Plotly.NET.GenericChart
open Plotly.NET.LayoutObjects
open Plotly.NET.StyleParam

  let r = [ 1; 2; 3; 4; 5; 6; 7 ] |> List.map ((*) 10000)
  let t = [ 0; 45; 90; 135; 200; 320; 184 ]
  let polar = Chart.LinePolar(r, t)
  polar
  |> Chart.withAngularAxis ( AngularAxis.init (Direction = Direction.Clockwise, Rotation = 90))
  |> fun x ->
    Chart.show x
    x
  |> toEmbeddedHTML
  |> printf "%s"
```
Will provide create the image, and print the generated HTML

simply run this example code to reproduce

### Expected behavior

In the produced HTML, there is a portion

var data=...
var layout=...
etc.

At the end of the var layout, a polar section is added, should formatted as such:
```json 
{"polar":{"angularaxis":{"direction":"clockwise","rotation":90}}}

```
The 0 degrees point is vertical, and angles increase clockwise as desired

### Actual behavior
The section described above is actually formatted as

```json 
{"polar":{"angularaxis":{"Direction":{"Case":"Clockwise"},"Rotation":90}}}
```
The image that is created is incorrect in: 0 axis is not rotated  around by 90degrees, the degrees increase counter clockwise (default behavior for both)

### Known workarounds

I don't know of any. I think DynamicObj could be used with the current package, but I have not tried that yet.

### Related information 

* Win11
* 2.0.0-preview.16
* ..Net 6.0.100

**Comment by FlippievanDyk** [comment]
I have actually already cloned the lib, and I have a working fix, which I will put in a PR soon. Mainly, I want to ask the question, if someone knows Plotly well, it seems that all style  should always be lower case? 

If so, I can expand my scope and look for other parameters that share the issue. I've only had problems with these, but that is not to say that there are not others...

**Comment by kMutagene** [comment]
The style params are always lower case in plotly, yes. Your fixes look good to me, thanks for taking a look at this ;) This kind of stuff happens sometimes to me when not taking enough care while copy pasting sorry :D
