### ISSUE TITLE
Document how to use colors

### ISSUE THREAD

**Issue by nhirschey** [plotly/Plotly.NET#260]
### Description

Thanks for the great library. Just an FYI: 

I can't find anything (obvious) on the website documenting how to use colors. I eventually figured it out by inspecting types but this would be a useful documentation addition, especially in the case of Column charts where the columns are styled with "Marker" which was unintuitive to me.

I got it to work with

```fsharp
  chart
  |> Chart.Column
  |> Chart.withMarkerStyle  (Color = Color.fromKeyword ColorKeyword.Black) 
```

### Repro steps

Browse the plotly.net side-bar for a page showing how to change colors (specifically for a column chart). I checked [column charts](https://plotly.net/02_1_bar-and-column-charts.html) first and then the [basics](https://plotly.net/00_0_basics.html) and then [display options](https://plotly.net/00_2_display-options.html) pages.

Using the "search" box in the side bar wasn't especially helpful. 

### Expected behavior

At least one example in the display options page would be useful. But for example, the parameter that I need to use in column charts (MarkerStyle) is not obvious so the long term goal might be to demonstrate colors on each page.

I recognize also that once the API is stable documenting the parameters in the Types (https://plotly.net/reference/plotly-net-chart2d-chart.html#Column) would help figure these things out.

### Related information 

* Windows 11
* .net 6
* #r "nuget: Plotly.NET, 2.0.0-preview.16"

**Comment by nhirschey** [comment]
Ok, so the type parameters are already documented in the [source](https://github.com/plotly/Plotly.NET/blob/bebb9d27fef2af43ee92af1dfea7830cec370bf7/src/Plotly.NET/ChartAPI/Chart2D.fs#L2716) but 

- the XML comments for the type parameters are not showing up in the ionide tooltips or on the fsdocs-generated API document [here](https://plotly.net/reference/plotly-net-chart2d-chart.html#Column).
- The [source link](https://github.com/plotly/Plotly.NET/blob/dev/src/Plotly.NET/ChartAPI/Chart2D.fs#L2053-2053) in the api documentation also takes us to the funnell type instead of the column chart type.

**Comment by kMutagene** [comment]
I have added xml docs recently for all chart constructors, this is not released yet though so this is why it is not showing up in the IDE and docs. I also changed and/or added many parameters as well, and unified the naming across them.

Regarding marker style being unintuitive for setting color, thats just how plotly works, not much we can do about that other than abstracting it in the parameters of chart constructors, which i think is looking pretty good now - so please hang on a little longer, the big release is coming soon ;)

**Comment by kMutagene** [comment]
Regarding color in general, i completely agree that there should be a documentation page solely for that, the type itself is very complex and has many different ways of usage

**Comment by nhirschey** [comment]
Yes, I know the library and site are very much under construction! And your work here is incredible.

A separate color page is a great idea.

**Comment by kMutagene** [comment]
https://plotly.net/00_7_working-with-colors.html contains color usage docs ;)

**Comment by nhirschey** [comment]
Looks great. I didn’t know about that color scale option. Thank you!
