### ISSUE TITLE
Make default outline for the Marker type darker in bar charts

### ISSUE THREAD

**Issue by nhirschey** [plotly/Plotly.NET#261]
### Description

When I upgraded some charts from beta5 to preview16, some bar/column charts with large numbers of observations became very hard to read because the marker outline color is too light. I think the marker outline should be darker.

I believe the fix would be to change `Trade2D.initBar` [here](https://github.com/plotly/Plotly.NET/blob/bebb9d27fef2af43ee92af1dfea7830cec370bf7/src/Plotly.NET/Templates/ChartTemplates.fs#L362) but I do not know what color you prefer.

### Repro steps

```fsharp
#r "nuget: Plotly.NET, 2.0.0-preview.16"
open Plotly.NET

let rnd = new System.Random()
let xy =
    let (h::t) = [ for i in 0..10_000 -> System.DateTime(1970, 1, 1, 0, 0, 0, 0).AddDays(i), rnd.NextDouble()-0.5 ]
    t
    |> List.scan (fun (dt1,y1) (dt2, y2) -> dt2, y1+y2) h

let plotThis (xy: seq<System.DateTime * float>) template =
    xy
    |> Chart.Column
    |> Chart.withTemplate template
    |> Chart.show

plotThis xy ChartTemplates.plotly
```

The result is a figure where the columns are nearly invisible.

<img width="442" alt="image" src="https://user-images.githubusercontent.com/5226115/150678105-39b30a6f-aadc-42a4-87de-9bb1f29f00c4.png">

### Expected behavior

If I use something darker for the outline color then I get a usable chart. I think this sets the outline to be the same as the default color.

```fsharp
open Plotly.NET.TraceObjects

let layoutModified = 
    Layout.init(
        PlotBGColor = Color.fromHex "#E5ECF6",
        Title = Title.init("Modified column outline")
    )

let traceTemplates = 
    [
        Trace2D.initBar (
            Trace2DStyle.Bar(            
                Marker =
                    Marker.init (
                        Outline = Line.init (Color = Color.fromHex "#636efa", Width = 0.5),
                        Pattern =
                            Pattern.init (
                                FillMode = StyleParam.PatternFillMode.Overlay,
                                Size = 10,
                                Solidity = 0.2
                            )
                    )
            )
        )
    ]

let myTemplate = Template.init(layoutModified, traceTemplates)

plotThis xy myTemplate
```

<img width="421" alt="image" src="https://user-images.githubusercontent.com/5226115/150678230-950e1dd5-1d45-428c-bd1b-8cf284c19b0e.png">

### Known workarounds

Manually set the outline color

### Related information 

* Windows 11
* "nuget: Plotly.NET, 2.0.0-preview.16"
* .net 6

**Comment by kMutagene** [comment]
I think we should not change the default template to keep it consistent across all versions of plotly. 

You can however modify the template and/or set a custom chart template. You can read more on that [here](https://plotly.net/00_5_defaults.html) and [here](https://plotly.net/00_4_templates.html).

If you want charts to look as they have before we introduced chart templates, you can set the `UseDefaults` parameter of any `Chart.*` function to false or set the global template to an empty template.

**Comment by nhirschey** [comment]
Ok, if this is the plotly default across all versions that's fine. Consistency across versions is a worthy goal (even if I disagree with the default ;)

Thank you for the pointers to template modification.
