### ISSUE TITLE
BoxFillColor in violin plot has no effect

### ISSUE THREAD

**Issue by dobretzberger** [plotly/Plotly.NET#263]
### Description
When creating a violin with a box inside, the color argument for the box is ignored. 

This is the code:

```fsharp
let y =  [2.; 1.5; 5.; 1.5; 3.; 2.5; 2.5; 1.5; 3.5; 1.]
let x = ["bin1";"bin2";"bin1";"bin2";"bin1";"bin2";"bin1";"bin1";"bin2";"bin1"]

let violin1 =
    Chart.Violin (
        x,y,
        ShowBox = true,
        BoxFillColor = Color.fromKeyword ColorKeyword.Red)
    
    
violin1
```

### Expected behavior

Box in violin should have the color passed as argument, Red in the given case.
### Actual behavior

Color has no effect, remains by the default. 

### Known workarounds

Create a boxplot and combine it with the violin

### Related information 
- Windows 10
- Plotly.NET, 2.0.0-preview.16
- .net48, FSharp.Core 5.0.2

**Comment by kMutagene** [comment]
Yep, that was a typo, thanks for reporting this!
