### ISSUE TITLE
Add Density-Scatter Plot

### ISSUE THREAD

**Issue by ZimmerD** [plotly/Plotly.NET#265]
### Description
The current example for [Histogram2D](https://plotly.net/04_4_2d-histograms.html) features an example of a combined Chart using a Histogram2DContour and Point Chart:

```

let histogramContour =
    [
        Chart.Histogram2DContour (x,y,Line=Line.init(Width=0.))
        Chart.Point(x,y,Opacity=0.3)
    ]
    |> Chart.combine

```

However, the resulting result has traces of different sizes, resulting in a slight gray, line on top of the chart (see docs). You can style the Chart to get rid of it, however I think it would be worthwhile to add a Chart type, which wraps the functionality to be able to write:

```
let histogramContour = Chart.DensityScatter (x,y) // naming not final. just suggestion    
```

and get a nicely styled version of the above.

**Comment by kMutagene** [comment]
@ZimmerD what do you think of the name `Chart.PointDensity` ?

**Comment by ZimmerD** [comment]
Sounds good to me!
