### ISSUE TITLE
Cannot disable violin points on preview.17

### ISSUE THREAD

**Issue by yigitl** [plotly/Plotly.NET#269]
### Description

Setting the `Points=StyleParam.BoxPoints.False` should disable the points, but it doesn't. 

![test](https://user-images.githubusercontent.com/93515153/156160208-6c55d2db-74d2-4774-91bf-ad4abcff0f2d.png)

### Repro steps

1. Run following:
```
#r "nuget: Plotly.NET, 2.0.0-preview.17"
#r "nuget: Plotly.NET.Interactive, 2.0.0-preview.17" 
    
open Plotly.NET

let arr = seq { for i in 0.0 .. 1.0 .. 100.0 -> if i < 80 then i / i else i - 80.0 } 
let names = Seq.map (fun x -> "bin") arr

Chart.Violin(
    names,
    arr, 
    Points=StyleParam.JitterPoints.False,
    PointPos=(-1.0) // this doesn't change the behavior, I've added it for clarity
)
```

### Expected behavior

Points shouldn't show up.

### Actual behavior

Points are showing up.

### Known workarounds

Sadly, I haven't found a workaround yet.

### Related information 

* Windows 10
* Plotly.NET, 2.0.0-Preview.17
* Plotly.NET.Interactive, 2.0.0-Preview.17
* DotNet 6.0.101

I'm using jupyter notebook, even though I don't think that is the problem, I'll list all the extensions and their versions belo.
* Jupyter v2022.1.1301854968
* Jupyter Notebook Renderers v1.0.6

**Comment by kMutagene** [comment]
Thanks for reporting this @yigitl ! I have fixed this and found a few other places where boolean style params where not set correctly. 

If you want to use a temporary fix for this until we make a new release, you can do it like this:

```fsharp
#r "nuget: Plotly.NET, 2.0.0-preview.17"
#r "nuget: Plotly.NET.Interactive, 2.0.0-preview.17" 
    
open Plotly.NET

let arr = seq { for i in 0.0 .. 1.0 .. 100.0 -> if i < 80 then i / i else i - 80.0 } 
let names = Seq.map (fun x -> "bin") arr

let violinChart =
    let violinTrace =
        Trace2D.initViolin(
            Trace2DStyle.Violin(
                X = names,
                Y = arr
            )
        )
    violinTrace?points <- false
    GenericChart.ofTraceObject true violinTrace

violinChart
|> Chart.show

```

![image](https://user-images.githubusercontent.com/21338071/156322681-fce0fc7f-ae8e-45d8-9e06-614836f05164.png)

**Comment by yigitl** [comment]
Thank you for the quick reply and workaround!
