### ISSUE TITLE
Add step-by-step documentation.

### ISSUE THREAD

**Issue by swapnilsaha-me** [plotly/Plotly.NET#274]
### Description

Please provide a documentation about how to run this library in my machine (windows or linux) and test the changes locally that I will change in the code.

### Documentation content

Following things can be the content:

1. What IDE I need to use,
2. What command I need to use to build the project.
3. How to see the changes that I will do in my code,

**Comment by kMutagene** [comment]
Hi @swapnilsaha-me. This sounds more like a general development issue than an issue with the library. I don't think we need to document a tutorial on how to get a development environment set up, that is not in the scope of this libraries documentation.

To get started with F#/.NET, you can follow this: https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/
You can use VSCode (all OS) or Visual Studio (on Windows/Mac only). 

The steps of how to build the project are laid out in the readme: https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/

There are several ways to test local changes to a library:
- create a separate application that references your local project (https://docs.microsoft.com/de-de/dotnet/core/tools/dotnet-add-reference)
- use this file https://github.com/plotly/Plotly.NET/blob/dev/src/Plotly.NET/Playground.fsx with interactive F# scripting
- build the nuget package and reference it in a new .NET interactive project (see for example the notebook files in this folder: https://github.com/plotly/Plotly.NET/tree/dev/src/Plotly.NET.Interactive)
