### ISSUE TITLE
issue with shapes and subplots

### ISSUE THREAD

**Issue by thomasd3** [plotly/Plotly.NET#276]
I have this code:
```
        [
            // first subplot
            [
                (candleChart @ pricesChart @ tradesChart)
                |> Chart.combine
                |> Chart.withShapes (zonesChartAnalysis @ liquidityLinesChart @ fairPriceLinesChart )
                |> Chart.withAxisAnchor (X = 1, Y = 1)
            ]
            |> Chart.combine
            
            // second subplot
            [
                ATRChart
                |> Chart.withShape
                    (LayoutObjects.Shape.init (StyleParam.ShapeType.Rectangle, firstCandle.Timestamp, lastCandle.Timestamp, 0.6, 0.1, Opacity = 1., Fillcolor = Color.fromKeyword ColorKeyword.Green))
                |> Chart.withAxisAnchor (X = 1, Y = 2)
            ]
            |> Chart.combine
        ]
        |> Chart.combine
        |> Chart.withConfig config
        |> Chart.withXAxis (
                LayoutObjects.LinearAxis.init(RangeSlider = LayoutObjects.RangeSlider.init(Visible = false), Range = StyleParam.Range.MinMax(firstTrade.Timestamp, lastCandle.Timestamp)
                )
            ) //, ShowGrid = false))
        |> Chart.withYAxis (
                LayoutObjects.LinearAxis.init(AutoRange = StyleParam.AutoRange.True, FixedRange = false, Domain = StyleParam.Range.MinMax(0.20, 1.00)),
                Id = StyleParam.SubPlotId.YAxis 1                
            )
        |> Chart.withYAxis (
                LayoutObjects.LinearAxis.init(AutoRange = StyleParam.AutoRange.True, FixedRange = false, Domain = StyleParam.Range.MinMax(0.00, 0.15)),
                Id = StyleParam.SubPlotId.YAxis 2                
            )

```

the point of interest is the second subplot:

            // second subplot
            [
                ATRChart
                |> Chart.withShape
                    (LayoutObjects.Shape.init (StyleParam.ShapeType.Rectangle, firstCandle.Timestamp, lastCandle.Timestamp, 0.6, 0.1, Opacity = 1., Fillcolor = Color.fromKeyword ColorKeyword.Green))
                |> Chart.withAxisAnchor (X = 1, Y = 2)
            ]
            |> Chart.combine

I am building a green rectangle shape in it and attaching it to the second subplot. 

But in the graph, it goes to the first subplot:

<img width="935" alt="image" src="https://user-images.githubusercontent.com/14313218/159816390-edd15eea-4fc4-4c84-be89-a16b2a753dc3.png">

It looks like, no matter what I do, the shapes are going to the first subplot.

**Comment by kMutagene** [comment]
Hi @thomasd3, please add a minimal code snippet for reproduction that i can execute on my local machine. Anyway, it looks to me like you are not using the 'Yref' property of the shape as i already noted in #272:

```fsharp
LayoutObjects.Shape.init (
    StyleParam.ShapeType.Rectangle, 
    firstCandle.Timestamp, 
    lastCandle.Timestamp, 
    0.6, 
    0.1, 
    Opacity = 1., 
    Fillcolor = Color.fromKeyword ColorKeyword.Green
)
``` 
should use `Yref = "y2"` if you want it to go on the second subplot

On another note, please join the discord server and ask how-to questions there if possible, i would prefer to keep github issues centered on missing implementations and bugs.
