### ISSUE TITLE
Docs for Plotly.NET via C#?

### ISSUE THREAD

**Issue by chrisxfire** [plotly/Plotly.NET#278]
I've been trying to use Plotly.NET with C#.  I'm doing my best to translate the document from F# to C#; this is working for the most part but there are some areas where I'm missing the mark.  Is there a source of Plotly.NET documentation specific to C# somewhere?

**Comment by kMutagene** [comment]
hey @chrisxfire 

The current plan regarding C# support is to completely rewrite the compatibility layer, basically adding real C# wrappers for all chart methods after the 2.0 release. As this will change/simplify the C# API considerably, i currently hesitate to invest the time of porting F# docs to C#, as they will be useless afterwards. 

So for now i am sorry that C# devs have to feel the pain of porting other .NET language code (a feeling almost exclusively reserved for F# devs usually 😆) if you have  specific questions, feel free to reach out in our discord server and ill look into it.

**Comment by chrisxfire** [comment]
@kMutagene thanks for the reply.  You're right, F# devs are usually the ones feeling this pain, so it's time for us to take our licks 😁 I can see how rewriting the docs is a fruitless effort with a pending rewrite of the compatibility layer.  But that's exciting!  Is this work tracked under #71 ?  I'd love to follow along.

**Comment by kMutagene** [comment]
I will write up a new roadmap issue once 2.0 is out, then you will find a separate issue for C# docs and the C# layer there.

**Comment by kMutagene** [comment]
@chrisxfire FYI the issue for tracking C# compatibility layer progress can now be found here: #285
