### ISSUE TITLE
Display multiple charts using Chart.Grid in C#

### ISSUE THREAD

**Issue by mdmoura** [plotly/Plotly.NET#280]
Using C# I have the following:

    List<Int32> xValues = Enumerable.Range(1, 500);
    List<Single> y1Values = getY1Values();
    List<Single> y2Values = getY2Values();  

How use Chart.Grid with C# to display the following 2 charts?

    GenericChart.GenericChart chart1 = Chart2D.Chart.Line<Int32, Single, String>(xValues, y1Values);

    GenericChart.GenericChart chart2 = Chart2D.Chart.Line<Int32, Single, String>(xValues, y2Values);

Will documentation in C# be available soon?

**Comment by kMutagene** [comment]
Chart.Grid still needs C# compatible stubs for directly calling it, as it currently returns an F# function. In the meantime if you really need it, here is how to use it (use the `Invoke` method on the returned function):

```csharp
using System;
using Plotly.NET;
using Microsoft.FSharp.Core; // use this for less verbose and more helpful intellisense
using Plotly.NET.LayoutObjects;

namespace Plotly.NET.Tests.CSharp
{
    class Program
    {
        static void Main(string[] args)
        {
            double[] x = new double[] { 1, 2 };
            double[] y1 = new double[] { 5, 10 };
            double[] y2 = new double[] { 10, 20 };

            GenericChart.GenericChart[] charts = {
                Chart2D.Chart.Line<double, double, String>(x, y1),
                Chart2D.Chart.Line<double, double, String>(x, y2)
            };

            Chart.Grid<GenericChart.GenericChart[]>(1, 2)
                .Invoke(charts)
                .Show();
        }
    }
}
```
![image](https://user-images.githubusercontent.com/21338071/165033566-16f273a2-5a00-4f92-8351-0140fa9a1697.png)
