### ISSUE TITLE
[v4] Roadmap

### ISSUE THREAD

**Issue by kMutagene** [plotly/Plotly.NET#282]
This issue acts as a roadmap aggregating the features exclusively for the next version of this library. 

Development of Plotly.NET 3.0 will be conducted on the `v3` branch

The following features are most likely not backwards compatible and cannot be added as feature versions for v2.

- [ ] migrate to immutable dynamic object - this makes all charts immutable, removing many confusing problems coming from mutation of charts) (#176)
- [ ] Separate into core and express package - Currently, there is a mix of low and high level APIs combined in a single package - Plotly.NET. In the future, especially when adding more and more high level APIs - it is beneficial to separate these in two packages, just as the python package did. (#209)

**Comment by MetARverse-Ian** [comment]
Would be nice to have support for maplibre-gl [maplibre-gl-js](https://github.com/maplibre/maplibre-gl-js)

**Comment by kMutagene** [comment]
@ianfoster99 that sounds like something that should/must be implemented in the base js library https://github.com/plotly/plotly.js/ , maybe you could open an issue there

**Comment by kMutagene** [comment]
closing this as i want a more dynamic approach for vNext issue tracking via milestones
