### ISSUE TITLE
Consistent naming of dynamic object properties "plot_bgcolor" and "paper_bgcolor"

### ISSUE THREAD

**Issue by smallstone77** [plotly/Plotly.NET#284]
### Description

Hi, I ran into this problem while using Plotly.Net from C#. I tried to set the background color of a layout via the SetValue() of the Layout class.  Using the init function this would look like this:

Layout layout = Layout.init<IConvertible>(PlotBGColor: Color.fromHex("#ADFF2F"));

But with SetValue() the naming of the property is slightly different.

### Expected behavior

Layout layout = new Layout();
layout.SetValue("plotbgcolor", Color.fromHex("#ADFF2F"));

### Actual behavior

Layout layout = new Layout();
layout.SetValue("plot_bgcolor", Color.fromHex("#ADFF2F"));

I'd propose to remove the "_" from dynamic properties in Layout.fs.
Thanks!

**Comment by kMutagene** [comment]
Hi there, you are mixing 2 API levels here, thats why it might seem confusing. 

We are constructing plotly.js json under the hood. There, the property is named "plot_bgcolor" (see: https://plotly.com/javascript/reference/layout/#layout-plot_bgcolor). 

This is not the way things are usually named in .NET APIs. So the parameter of our high level, type-safe API for constructing Layouts is `PlotBGColor` . 

However when you leave that high level API using dynamic object, you have to make sure that the properties are correctly named for consumption in plotly.js (so it has to be `"plot_bgcolor"`)

**Comment by smallstone77** [comment]
Thank you very much. Yes, I mixed that up :-)
