### ISSUE TITLE
Annotations in grid are all displayed within first chart

### ISSUE THREAD

**Issue by kentcb** [plotly/Plotly.NET#286]
### Description

Annotations assigned to individual charts displayed within a grid are all displayed within the first chart within the grid.

### Repro steps

```fsharp
let createChildChart name =
    let annotation =
        Annotation.init(
            3,
            3,
            ShowArrow = false,
            Text = $"Annotation: {name}",
            XAnchor = StyleParam.XAnchorPosition.Left
        )

    let chart =
        Chart.Line(
            [1;2;3;4;5],
            [1;2;3;4;5],
            Name = name
        )
        |> Chart.withAnnotation(annotation)

    chart

[
    createChildChart "First"
    createChildChart "Second"
]
|> Chart.Grid(2, 1)
|> Chart.withLegend false
|> Chart.show
```

### Expected behavior

Each annotation should appear in the chart to which it is added.

### Actual behavior

![image](https://user-images.githubusercontent.com/1901832/166416337-7adb762e-6a3c-42ed-8cde-0a7678bb6a89.png)

### Known workarounds

None.

### Related information 

* Windows 10
* `Plotly.NET` `2.0.0`
* .NET Core

**Comment by kMutagene** [comment]
Hi @kentcb , this behavior is expected although admittedly not immediately obvious - the default reference axis for annotation coordinates are `x1` and `y1` (the axes of your first chart in the grid). At the point where you initialize your charts, they both have a `x1` and `y1` axis. `Chart.Grid` changes the axis anchor of the second chart to be `y2` without adjusting the annotation references. If you want the annotations to calculate their positions in respect to other axes, the `XRef` and `YRef` parameters must be set (i'd also suggest adding the annotations after creating the grid chart in that case, see also #272):

```fsharp
#r "nuget: Plotly.NET"

open Plotly.NET
open Plotly.NET.LayoutObjects
[
    Chart.Line [1,2 ; 3,4]
    Chart.Line [1,2 ; 3,4]
]
|> Chart.Grid(2,1)
|> Chart.withAnnotations [
    Annotation.init(Text = "x1y1", XRef = "x1", YRef = "y1", X = 2, Y = 3 )
    Annotation.init(Text = "x1y2", XRef = "x1", YRef = "y2", X = 2, Y = 3 )
]
|> Chart.show
``` 

![image](https://user-images.githubusercontent.com/21338071/166913536-ff23a958-22ab-4b01-99b8-55c0838cf0a3.png)

**Comment by kentcb** [comment]
Thanks @kMutagene. I was able to get my grid to work with annotations. However, just wondering if there's some way to take ownership of what ref is assigned by `Chart.Grid` (or `Chart.Single.Stack`). It feels a bit "magical" to me at the moment, having to know that `Chart.Grid` will assign refs in a certain way. Also wondering what it means by composing a grid within a grid...

**Comment by kMutagene** [comment]
`Chart.Grid` is a 'magic' function indeed, it maps over all traces, determines the trace type and adjusts the respective subplot properties. It does a lot of work implicitly, but that's the thing with high level APIs. You also cannot control gridsize, and grid-within-grid wont work. For that you need more control, you just have to know how (watch out for #273, which will eventually bring docs for this). 

An example can be seen in #272. I adapted it for here a bit:

```fsharp
#r "nuget: Plotly.NET"

open Plotly.NET
open Plotly.NET.LayoutObjects
[
    Chart.Line [1,2 ; 3,4]
    |> Chart.withAxisAnchor(X=1, Y=1) // determine which axis this subplot uses
    Chart.Line [1,2 ; 3,4] 
    |> Chart.withAxisAnchor(X=1, Y=2) // determine which axis this subplot uses
]
|> Chart.combine // combine thae charts, but not with Chart.Grid!
|> Chart.withYAxis(
    LinearAxis.init(Domain = StyleParam.Range.MinMax(0.,0.65)), // the portions of the plot spanned by this axis
    Id = StyleParam.SubPlotId.YAxis 1 // the id of this axis (used by the axis anchors above)
)
|> Chart.withYAxis(
    LinearAxis.init(Domain = StyleParam.Range.MinMax(0.7,1.)), // the portions of the plot spanned by this axis
    Id = StyleParam.SubPlotId.YAxis 2 // the id of this axis (used by the axis anchors above)
)
|> Chart.withAnnotations [
    Annotation.init(Text = "x1y1", XRef = "x1", YRef = "y1", X = 2, Y = 3 ) 
    Annotation.init(Text = "x1y2", XRef = "x1", YRef = "y2", X = 2, Y = 3 ) 
]
|> Chart.show
```

![image](https://user-images.githubusercontent.com/21338071/167083132-6a1a4ba2-1929-409c-aed8-13f965eee3ab.png)

**Comment by kentcb** [comment]
OK, that makes sense. I might end up using `combine` instead. For the record, the cleanest I've been able to get the grid code is to do something like this:

```fsharp
let yAxisId1 = 1
let yAxisId2 = 2

let xAxisId1 = 1

let createChildChart name xAxisId yAxisId =
    let annotation =
        Annotation.init(
            3,
            3,
            ShowArrow = false,
            Text = $"Annotation: {name}",
            XAnchor = StyleParam.XAnchorPosition.Left,
            XRef = (StyleParam.LinearAxisId.X xAxisId).ToString(),
            YRef = (StyleParam.LinearAxisId.Y yAxisId).ToString()
        )

    Chart.Line(
        [1;2;3;4;5],
        [1;2;3;4;5],
        Name = name
    )
    |> Chart.withAnnotation(annotation)
    |> Chart.withXAxisStyle(Id = StyleParam.SubPlotId.XAxis xAxisId)
    |> Chart.withXAxisStyle(Id = StyleParam.SubPlotId.YAxis yAxisId)

[
    createChildChart "First" xAxisId1 yAxisId1
    createChildChart "Second" xAxisId1 yAxisId2
]
|> Chart.SingleStack(Pattern = StyleParam.LayoutGridPattern.Coupled)
|> Chart.withLegend false
|> Chart.show
```

It feels off to me using ints instead of proper IDs, but I need a `SubPlotId` in one case and a `LinearAxisId` in the other (to get the correct ref string).

**Comment by kMutagene** [comment]
> It feels off to me using ints instead of proper IDs, but I need a SubPlotId in one case and a LinearAxisId in the other (to get the correct ref string).

That's because plotly.js has 2 ways of handling this, subplotId is "yaxis2" and used as field of the layout object for identifying axes, while references to these axes are only e.g. "y2" . Not really much we can do about this other than maybe changing the type of `XRef` from string to `LinearAxisId`.

**Comment by kentcb** [comment]
Thanks @kMutagene. By using `Chart.combine`, I've gotten _real close_ now to what I'm after, but a second x axis isn't working as I'd hoped. Am I doing something obviously wrong here? I want the top chart to have its x axis rendered underneath it rather than superimposed over the x axis used for the other 3 charts.

```fsharp
let random = System.Random(1234)

let repro () =
    let createChildChartType1 xAxisId yAxisId =
        let yAxis =
            LinearAxis.init (
                ShowLine = true,
                ShowGrid = true
            )

        Chart.SplineArea(
            [ 0.. 100 ],
            [ 0.. 100 ] |> List.map (fun _ -> random.NextDouble() * 120.)
        )
        |> Chart.withXAxisStyle(Id = StyleParam.SubPlotId.XAxis xAxisId)
        |> Chart.withYAxis(yAxis, Id = StyleParam.SubPlotId.YAxis yAxisId)
        |> Chart.withAxisAnchor(X = xAxisId, Y = yAxisId)

    let createChildChartType2 xAxisId yAxisId =
        let yAxis =
            LinearAxis.init (
                ShowLine = true,
                ShowGrid = true
            )

        Chart.Line(
            [0 .. 30] |> List.map (fun o -> DateTime.UtcNow.AddDays(o)),
            [ 0 .. 30 ] |> List.map (fun _ -> random.NextDouble() * 90. + 35.)
        )
        |> Chart.withXAxisStyle(Id = StyleParam.SubPlotId.XAxis xAxisId)
        |> Chart.withYAxis(yAxis, Id = StyleParam.SubPlotId.YAxis yAxisId)
        |> Chart.withAxisAnchor(X = xAxisId, Y = yAxisId)

    let xAxisId1 = 1
    let xAxisId2 = 2
    let yAxisId1 = 1
    let yAxisId2 = 2
    let yAxisId3 = 3
    let yAxisId4 = 4

    [
        createChildChartType1 xAxisId1 yAxisId1
        createChildChartType1 xAxisId1 yAxisId2
        createChildChartType1 xAxisId1 yAxisId3

        createChildChartType2 xAxisId2 yAxisId4
    ]
    |> Chart.combine
    |> Chart.withXAxisStyle(
        Id = StyleParam.SubPlotId.YAxis xAxisId1,
        Domain = (0., 0.75)
    )
    |> Chart.withXAxisStyle(
        Id = StyleParam.SubPlotId.YAxis xAxisId2,
        Domain = (0.75, 1.)
    )
    |> Chart.withYAxisStyle(
        Id = StyleParam.SubPlotId.YAxis yAxisId1,
        Domain = (0, 0.2)
    )
    |> Chart.withYAxisStyle(
        Id = StyleParam.SubPlotId.YAxis yAxisId2,
        Domain = (0.25, 0.45)
    )
    |> Chart.withYAxisStyle(
        Id = StyleParam.SubPlotId.YAxis yAxisId3,
        Domain = (0.5, 0.7)
    )
    |> Chart.withYAxisStyle(
        Id = StyleParam.SubPlotId.YAxis yAxisId4,
        Domain = (0.75, 0.9)
    )
    |> Chart.withSize (Width = 1920, Height = 1080)
```

![image](https://user-images.githubusercontent.com/1901832/167233045-7a3e47a4-265b-4660-bbee-45f5536cc517.png)

**Comment by kMutagene** [comment]
~~You are using `Chart.withXAxisStyle`, which styles the same axis over and over. You need to create actual axis objects with the correct domains and add them via `Chart.withXAxis`  (see the example i posted)~~ (seems like styling with the correct Ids also works). I suggest using `Chart.withAxis` nonetheless, it gives you more options. You are at the point where you are doing things that are so low-level it makes sense to consult the javascript docs and translate it into F#. The respective docs can be found here:  https://plotly.com/javascript/subplots/#multiple-custom-sized-subplots

The trick seems to be to additionally setting the `Anchor` partameter of the axis pairs, which will orient them at each other. also, the `Domain` parameter of the XAxis objects are in respect to their horizontal proportions, so i don't think you wanna change that. here is a more simple example that should get you running:

```fsharp
#r "nuget: Plotly.NET"

open Plotly.NET
open Plotly.NET.LayoutObjects
[
    Chart.Line [1,2 ; 3,4]
    |> Chart.withAxisAnchor(X=1, Y=1) // determine which axis this subplot uses
    Chart.Line [1,2 ; 3,4] 
    |> Chart.withAxisAnchor(X=2, Y=2) // determine which axis this subplot uses
]
|> Chart.combine // combine thae charts, but not with Chart.Grid!
|> Chart.withYAxis(
    LinearAxis.init(Domain = StyleParam.Range.MinMax(0.,0.65)), // the portions of the plot spanned by this axis
    Id = StyleParam.SubPlotId.YAxis 1 // the id of this axis (used by the axis anchors above)
)
|> Chart.withYAxis(
    LinearAxis.init(Domain = StyleParam.Range.MinMax(0.7,1.)), // the portions of the plot spanned by this axis
    Id = StyleParam.SubPlotId.YAxis 2 // the id of this axis (used by the axis anchors above as well as the anchor of the x axis.)
)
|> Chart.withXAxis(
    LinearAxis.init(
        Anchor = StyleParam.LinearAxisId.Y 2 // anchor at the secdond y axis
    ),
    Id = StyleParam.SubPlotId.XAxis 2 // the id of this axis (used by the axis anchors above)
)
|> Chart.show
```

![image](https://user-images.githubusercontent.com/21338071/167287054-e11b9a45-7ebe-4104-8c2b-a25f5e51ea2d.png)

**Comment by kentcb** [comment]
Awesome! Thanks @kMutagene!
