### ISSUE TITLE
How do I remove Aa from the legend?

### ISSUE THREAD

**Issue by spatel3-pcsa** [plotly/Plotly.NET#290]
### Description

I have created multiple Traces with mode as text.  I do not want to show symbols and instead show Alpha characters.  When doing this I see **Aa** in the legend.

### Repro steps

Trace overlayTrace = new Trace("scatter");
overlayTrace.SetValue("x", x);
overlayTrace.SetValue("y", y);
overlayTrace.SetValue("name", $"{alphachar} {series}");
overlayTrace.SetValue("mode", "text");
overlayTrace.SetValue("text", alphachar);

### Expected behavior

Remove **Aa** when only Text is shown and no symbol.

![image](https://user-images.githubusercontent.com/105985143/169666649-10bf72c7-e7bf-486c-9f81-ce0dc99333e7.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/105985143/169666423-e94f8b93-b5fa-4db6-adac-c5774ab88736.png)

### Known workarounds

I am searching for the solution and some suggested updating the plotly cdn to the latest will resolve the issue.  Is there a way to update the cdn in Plotly.NET?

### Related information 

* Windows Server x64
* Plotly.NET
* .NET Framework 4.5

**Comment by kMutagene** [comment]
The issues that were solved for plotly.js 2.0.0 was this one here: https://github.com/plotly/plotly.js/issues/5679 , which only removes "Aa" for traces with mode "something+text", not "text". While we should offer users changing the cdn version in the future, Plotly.NET 2.0.0 currently uses plotly.js 2.6.3, so the cdn is not the problem (also, `Aa` is still displayed when using the most recent plotly.js version).

I have skimmed through the plotly.js docs and have not found a way to do what you are trying here. If you can link a js or python sample that can do it, i can help translating it.

**Comment by kMutagene** [comment]
closing until we get an example, until then i assume that this is just not supported by plotly.js itself

**Comment by spatel3-pcsa** [comment]
Thank you, Kevin, for looking into this.  I will be looking forward to a solution to this.  We use the alphabet as a symbol in all our plots.

***@***.***________________________________________________________________
Best Regards,
Sanjay Patel
Senior Software Engineer
Intel Corporation
