### ISSUE TITLE
Anybody know how to export a point chart?

### ISSUE THREAD

**Issue by tiger2014** [plotly/Plotly.NET#291]
I want to export a arrowup and red point chart, but 

var buyPoit = Chart2D.Chart.Point<DateTime, decimal, string>(BackTestResult.Select(s => s.baTime).ToArray(), BackTestResult.Select(s => s.buyPrice).ToArray(), "Buy")
            .WithShape(MarkerSymbol: MarkerSymbol.ArrowBarUp, Color: Plotly.NET.Color.fromString("red"));

not work.

I also can't display the chart:

        var chart = Chart.Combine(new[] { KLines, buyPoit }).WithSize(1200, 400).WithMargin(Margin.init<int, int, int, int, int, bool>(1, 1, 60, 1, 1, false))
            .WithTitle("MACD using EMA")

It will be better, if there are some sample for C#

**Comment by kMutagene** [comment]
Hi @tiger2014 

If you think there is a bug or something not supported in C# please reopen this issue and add a well-formatted, reproducible code example. Otherwise i would suggest heading to our discord server for basic help.

**Comment by tiger2014** [comment]
Thanks
