### ISSUE TITLE
how to draw a point chart with data including null?

### ISSUE THREAD

**Issue by tiger2014** [plotly/Plotly.NET#292]
I have 2 array , one is [1,2,3,4,56,7,8], the other is [11,12,0, 14,0,17,0]. I don't want to draw value 0 when I combine the 2 array in one chart.

What can I do?

Thanks

**Comment by kMutagene** [comment]
easiest approach would be filtering the values before visualization.

**Comment by tiger2014** [comment]
Thanks.
