### ISSUE TITLE
Is it possible to add watermark to a plot?

### ISSUE THREAD

**Issue by ai-fwd** [plotly/Plotly.NET#30]
Firstly, great work on this library! Love using it.

I'm trying to recreate this example: https://plot.ly/javascript/layout-template/#add-named-container-array-items

But I don't see a way to add Images to the Layout as they have done. Is there another way to get a watermark on the plot?

Thanks.

**Comment by kMutagene** [comment]
Hi @ai-fwd,

Happy that you like it!

Not nearly all options of the original plotly library are wrapped in a typesafe manner. However, we are able to recreate any javascript example by using the dynamic object stlye (the type safe functions are infact just abstractions of this style), which you can create analogously to the javascript examples. While i could not get the templates to work quickly, using background images in the layout is pretty straight forward:
```

type LayoutImage () =
    inherit DynamicObj ()

let image1 = 
    let tmp = LayoutImage()
    tmp?name    <- "watermark_1"
    tmp?source  <- "https://raw.githubusercontent.com/michaelbabyn/plot_data/master/benzene.png"
    tmp?xref    <- "paper"
    tmp?yref    <- "paper"
    tmp?x       <- 0.40
    tmp?y       <- 0.9
    tmp?sizex   <- 0.7
    tmp?sizey   <- 0.7
    tmp?opacity <- 0.1
    tmp?layer   <- "below"
    tmp

let layoutUsingImage =
    let layout = Layout.init()
    layout?images <- [image1]
    layout

Chart.Line(x=[0; 1; 2; 3; 4; 5],y=[2; 4; 3; 0; 5; 6])
|> Chart.withLayout layoutUsingImage
|> Chart.Show
```

Rendered Chart:

![image](https://user-images.githubusercontent.com/21338071/78012357-1fb33f80-7345-11ea-9638-5a06a4309c63.png)

Regarding templates, i think it would be quite useful having those, i will look into it when i find time

**Comment by kMutagene** [comment]
See 
layout images: https://plotly.net/01_5_layout_images.html 
templates: https://plotly.net/00_4_templates.html
