### ISSUE TITLE
Marker colors do not work in bar chart.

### ISSUE THREAD

**Issue by jim108dev** [plotly/Plotly.NET#303]
### Description

I am trying to get a bar chart with different colors for each bar with f# interactive notebooks.

### Repro steps

Please provide the steps required to reproduce the problem

1. Create F# notebook in VS Code

2. Run code

```fsharp
#r "nuget: Plotly.NET, 2.0.0"
#r "nuget: Plotly.NET.Interactive, 2.0.0"
open Plotly.NET 
open Plotly.NET.TraceObjects

let green = Color.fromRGB 0 255 0
let red = Color.fromRGB 255 0 0
  
let values = [20; 14]
let keys   = ["Product A"; "Product B"]
let cols = [red;green]

Chart.Column(values,keys)
|> Chart.withMarker(Marker.init(Colors=cols))
``` 

### Expected behavior

First bar red, second green.

### Actual behavior

Both are blue.

### Related information 

* Operating system: Debian 10.12
* Branch: Plotly.NET, 2.0.0
* .NET Runtime, CoreCLR or Mono Version:
Microsoft.NETCore.App 6.0.4 
SDK 6.0.202

**Comment by jim108dev** [comment]
It is not `Colors`, it is 
```fsharp
    Color=Color.fromColors [ // one color for each individual bar
            Color.fromKeyword Salmon
            Color.fromKeyword SteelBlue
            Color.fromKeyword Azure
        ]
``` 
Nevermind!

**Comment by kMutagene** [comment]
Yeah i know it is a bit confusing, but Marker has both these fields, with `Colors` being used for section colors in e.g. Pie traces. Not much we can do here to make it more obvious.
