### ISSUE TITLE
Prerelease build on each push to main branch

### ISSUE THREAD

**Issue by WhiteBlackGoose** [plotly/Plotly.NET#308]
The idea is to be able to access the latest features without having to wait for the release.

The way I suggest we make it is to make a workflow on push to `dev`, which would pack and send a new version to `myget.org` (to differentiate from `nuget`).

The alternative is to have it on nuget too (on every push it would unlist all old prerelease builds and list only the new one)

**Comment by kMutagene** [comment]
In general this would be cool. How can we manage versioning there? or do we just add a build server number behind the current package version?

**Comment by WhiteBlackGoose** [comment]
Closed by #315
