### ISSUE TITLE
Plotly.NET Publicity and Thanks!

### ISSUE THREAD

**Issue by JakeRadMSFT** [plotly/Plotly.NET#326]
Hey All! 
Just a heads up that Plotly.NET was featured on a stream today along with VS's Notebook Editor:
https://www.youtube.com/watch?v=WfozTizHMlM

Thanks so much for building the library and working to add C# bindings and getting the libraries signed <3<3!!

**Comment by kMutagene** [comment]
Wow pretty cool to see Scott talking about this library!

**Comment by WhiteBlackGoose** [comment]
:tada:
