### ISSUE TITLE
[Feature Request]  Directed network in 3D

### ISSUE THREAD

**Issue by GeorgeS2019** [plotly/Plotly.NET#339]
Is there interest to make [Plotly:cytoscapejs](https://github.com/plotly/react-cytoscapejs) available to Plotly.NET?

Relevant[ Plotjs discussions: [Feature Request] Directed network in 3D](https://github.com/plotly/plotly.js/issues/4869)

![msedge_lahSYjk5ug](https://user-images.githubusercontent.com/49812372/184486581-7bc073a8-a1b0-4a2a-a8bf-963cb381a926.gif)

**Comment by kMutagene** [comment]
hi @GeorgeS2019 this does not fit in the scope of the Plotly.NET base library, as it does not seem to be implemented in base plotly.js as well (the issue you linked does not seem to be resolved/implemented). 

Anyways, the extension you linked uses [Cytoscape.js](http://js.cytoscape.org/), for which there already exists a direct bindings library for .NET in the fslab stack (https://fslab.org/Cyjs.NET/).
