### ISSUE TITLE
Method names should use PascalCase rather than camelCase to be more F# and .NET idiomatic

### ISSUE THREAD

**Issue by bmitc** [plotly/Plotly.NET#340]
### Description

Several methods, such as the static method [`Chart.withXAxisStyle`](https://github.com/plotly/Plotly.NET/blob/d36b043fce159ad7f28eadc0088e79ddba89ff12/src/Plotly.NET/ChartAPI/Chart.fs#L1098) use camelCase. However, the convention for F# is to camelCase functions but then PascalCase members.

### Repro steps

n/a

### Expected behavior

Members (properties and methods) should be PascalCase.

### Actual behavior

Members are camelCase.

### Known workarounds

n/a

### Related information 

n/a

**Comment by kMutagene** [comment]
All of these members are returning functions, not sure if this is 'violating' conventions too much but technically you are correct.

However, i currently do not plan to introduce another breaking major version increase too soon. Feel free to submit a PR for this though.

**Comment by nhirschey** [comment]
The style guide allows lower case static members.

> Sometimes you may wish to name something in one style for F# consumers (such as a static member in lower case so that it appears as if it were a module-bound function) ...
- [F# style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/component-design-guidelines#consider-using-compiledname-to-provide-a-net-friendly-name-for-other-net-language-consumers)

**Comment by kMutagene** [comment]
>Sometimes you may wish to name something in one style for F# consumers (such as a static member in lower case so that it appears as if it were a module-bound function)

This describes what we were trying to achieve more eloquently than i could have said it. I'll close this for now, thanks @nhirschey . 

@bmitc if you however see other instances where we could clash with the official style guide, feel free to reach out again!
