### ISSUE TITLE
Plotly.NET.Interactive: "show" function is opening chart in a browser tab

### ISSUE THREAD

**Issue by rodrigo455** [plotly/Plotly.NET#341]
### Description

Plotly.NET.Interactive is not working, "show" function is opening chart in a browser tab, not as ouput of a notebook cell

There is no:
"Added Kernel Extension including formatters for Plotly.NET charts"

after:
"Loading extensions from Plotly.NET.Interactive.dll"

### Repro steps

Please provide the steps required to reproduce the problem

1. install Jupyter lab and .net interactive with:
    ```sh
    # Install jupyterlab to default Python interpreter
    pip install jupyterlab
    # Install Dotnet Interactive dotnet tool
    dotnet tool install -g Microsoft.dotnet-interactive
    # Get Dotnet Interactive to register kernels with Jupyter  
    dotnet interactive jupyter install
    ```

3. create a .ipynb notebook

4.  create a cell with the following content and run:
    ```f#
    #r "nuget: Plotly.NET, *-*"
    #r "nuget: Plotly.NET.Interactive, *-*"

    open Plotly.NET
    let xData = [0. .. 10.]
    let yData = [0. .. 10.]
    let myFirstChart = Chart.Point(xData,yData)
    myFirstChart
    |> Chart.show
    ```

### Expected behavior

Chart is shown in the cell output

### Actual behavior

Chart opens in a browser tab

### Known workarounds

I don't know

### Related information 

* WSL Ubuntu-20.04
* Plotly.NET 3.0.0, Plotly.NET.Interactive 3.0.2 ... tried different versions none of them worked
* microsoft.dotnet-interactive (version '1.0.340501')
* .NET 6.0

**Comment by rodrigo455** [comment]
I see that this is the expected behavior for the "show" function

**Comment by kMutagene** [comment]
> I see that this is the expected behavior for the "show" function

correct, to see the chart in the notebook, just end the cell with the chart itself (in your example, simply remove the last line)

**Comment by gmkado** [comment]
@kMutagene What if I have a function that generates a plot and I want to call this multiple times within a cell and get multiple plots in the cell output?  Is that not possible right now?

**Comment by kMutagene** [comment]
@gmkado thats absolutely possible, there are multiple ways of creating subplots: https://plotly.net/01_2_multiple-charts.html
