### ISSUE TITLE
Importing a Map Layout in C#

### ISSUE THREAD

**Issue by shuganth** [plotly/Plotly.NET#354]
I am using C# to generate a map which show the density of the people.

            IEnumerable<string[]>? lines = File.ReadAllLines(@"C:\Users\axxx\Downloads\2011_us_ag_exports.csv").Select(a => a.Split(','));
            IEnumerable<string[]>? lines2 = File.ReadAllLines(@"C:\Users\axxxxx\Downloads\fips.csv").Select(a => a.Split(','));
            List<string> Locationcode = new List<string>();
            List<string> totalexports = new List<string>();
            foreach (var lin in lines2)
            {
                Locationcode.Add(lin[0]);
                totalexports.Add(lin[1]);
            }

            var geoJson = JsonConvert.DeserializeObject(File.ReadAllText(@"C:\Users\axxx\Downloads\fips4.json"));/
            var maps2 = ChartMap.Chart.ChoroplethMap<string, string>(locations: list, z: list2, LocationMode: 
            StyleParam.LocationFormat.GeoJson_Id, GeoJson: geoJson, ShowLegend: true, UseDefaults: false);
            maps2.Show();
I am looking to use zip3 with with the layout of https://github.com/mathbiol/sparcs/blob/master/zip3.geojson or can we use the shp.file to change the map if so could you please help out to change the map layout.
![Picture1](https://user-images.githubusercontent.com/51713075/186368768-71bf1927-d29a-4635-a8a8-df87d0369e7c.png)

This is generated in R using ggplot but i need to do in C# . Can you please help?

**Comment by kMutagene** [comment]
Again i will ask kindly to head over to the discord server (https://discord.gg/k3kUtFY8DB) for questions like this and keep github issues focused on bug reports and feature requests
