### ISSUE TITLE
Documentations on plotly.com are not up to date

### ISSUE THREAD

**Issue by zyzhu** [plotly/Plotly.NET#356]
Just browsed the official website of plotly. I noticed the documentations of F# version are still using the preview version.
![image](https://user-images.githubusercontent.com/7053696/189796561-89619959-3cbe-410b-9ab2-5a3081f37db6.png)

**Comment by kMutagene** [comment]
For now i don't recommend using the docs from that page. Plotly once put some effort into porting the docs from https://plotly.net to their own docs architecture (of which you see the partial results), but since they stopped that effort it will not get updated for the time being.
