### ISSUE TITLE
Chart.Candlestick Increasing/Decreasing args don't set any styling

### ISSUE THREAD

**Issue by neilyoung2008** [plotly/Plotly.NET#369]
[plotly-candlestick.zip](https://github.com/plotly/Plotly.NET/files/10833919/plotly-candlestick.zip)

The zip attachment is a jupyter file which include reproducible code example.
The output candlestick used the default  color for increse/decrease kline，not the custom colors in the code.

#229 

@kMutagene

**Comment by kMutagene** [comment]
Thanks for reporting this, this seems to be indeed buggy. For reference, the `MarkerColor` attribute should be named `FillColor` as of the latest plotly spec (https://plotly.com/javascript/reference/candlestick/#candlestick-increasing-fillcolor). I'll look into this.

**Comment by kMutagene** [comment]
Thanks again for reporting this. The fix is live in the next version. until then, you can set the correct styling via dynamic object style like this:

```csharp
var upcolor = Color.fromString("red");   
var dncolor = Color.fromRGB(250,235,196); 

var open = new[] {15, 20};
var high = new[] {18, 20};
var low = new[] {14, 16};
var close = new[] {17, 18};
var date = new[]{DateTime.Now, DateTime.Now.AddDays(1) };
var volume = new[] {20, 21};

var increasing = FinanceMarker.init();
increasing.SetValue("line",Line.init(Color:upcolor, Width:1, Dash : StyleParam.DrawingStyle.Solid));
increasing.SetValue("fillcolor",upcolor);

var decreasing = FinanceMarker.init();
decreasing.SetValue("line",Line.init(Color:dncolor, Width:1, Dash : StyleParam.DrawingStyle.Solid));
decreasing.SetValue("fillcolor",dncolor);

var candlestick = Chart2D.Chart.Candlestick<int, int, int, int, DateTime, string>
(
    open : open, 
    high : high, 
    low  : low, 
    close: close, 
    X : date, 
    Name: "K", 
    Increasing : increasing,
    Decreasing : decreasing, 
    ShowLegend : false,    
    Line : Line.init(Width : 0.5),                                
    UseDefaults : false
);

candlestick
```

![image](https://user-images.githubusercontent.com/21338071/221432940-95130535-8524-496b-a197-4b2cbc8e1981.png)
