### ISSUE TITLE
can't zoom in yAxis candle stick chart

### ISSUE THREAD

**Issue by hoangdungt2** [plotly/Plotly.NET#37]
hi, I follow this example : http://muehlhaus.github.io/FSharp.Plotly/candlestick.html to plot the candle stick, but I can't seem to zoom in yAxis. Because I have a lot of data hence the fix-yaxis makes some candle to be very flat and I can seem to zoom in by y axis.

**Comment by kMutagene** [comment]
Hi @hoangdungt2 ,

That was indeed a shortcoming of the Candlestick plot, as it does not give you the option to hide the rangeslider. I implemented rangesliders for linear axis 544641492195b1938697721b72814e0187a6c979 , and you can use them like this:

Lets say you take the example you used from the docs:

```
let ch1 = 
    candles 
    |> Chart.Candelstick
```

You can now initialize a rangeSlider and add it to the plot:
```

let rangeslider = RangeSlider.init(Visible=false)

ch1 
|> Chart.withX_AxisRangeSlider rangeslider
|> Chart.Show
```

while you obviously loose the rangeslider, you can now zoom into the yAxis:

![image](https://user-images.githubusercontent.com/21338071/83357898-abf6d880-a36f-11ea-8140-0288042fb909.png)

I hope this helps you. If you need the rangeslider, you may need to play around with the RangeSlider type.

This is available in the preview package [1.2.3-beta](https://www.nuget.org/packages/FSharp.Plotly/1.2.3-beta)

Let me know if this helped you!

**Comment by hoangdungt2** [comment]
hi Kevin, thanks for the quick reply. 
Your solution is perfect, I also always want to get rid of the rangeslider but did not see any option before. Just update to the latest preview and it works perfectly 👍

**Comment by kMutagene** [comment]
glad i could help!
