### ISSUE TITLE
Exception after updated Plotly.NET to version 4.0.0 from version 3.0.1 due to dependency on a non-strong named assembly

### ISSUE THREAD

**Issue by kunjiangkun** [plotly/Plotly.NET#371]
### Description

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for '<StartupCode$Plotly-NET>.$Defaults' threw an exception.
  Source=Plotly.NET
  StackTrace:
   at Plotly.NET.Defaults.set_DefaultTemplate(Template value)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Test.Program.<Main>(String[] args)

  This exception was originally thrown at this call stack:

Inner Exception 1:
FileLoadException: Could not load file or assembly 'Giraffe.ViewEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

Please provide a succinct description of your issue.

### Repro steps

Please provide the steps required to reproduce the problem

There is only one line of test code:
Defaults.DefaultTemplate = ChartTemplates.lightMirrored;

### Expected behavior

Please provide a description of the behavior you expect.

### Actual behavior

Please provide a description of the actual behavior you observe. 

### Known workarounds

Please provide a description of any known workarounds.

### Related information 
using .Net Framework 4.8.

**Comment by kunjiangkun** [comment]
Not sure if it's related but the Giraffe.ViewEngine 1.4.0 release has version 1.0.0 in the DLL.

**Comment by kMutagene** [comment]
Oh man, Giraffe.ViewEngine is not a strong named assembly 😢 This is the exact type of shit i hoped will not happen due to us adopting strong naming. Now i have to beg those maintainers to adopt strong naming too, or implement a view engine myself in this repo

**Comment by kMutagene** [comment]
Thanks for reporting this though, i think there is not much you can do to make it work. I think there is something called binding redirects for netfx.

**Comment by kMutagene** [comment]
@kunjiangkun does adding https://github.com/dsplaisted/strongnamer to your solution resolve the issue?

**Comment by kunjiangkun** [comment]
> @kunjiangkun does adding https://github.com/dsplaisted/strongnamer to your solution resolve the issue?

Adding strongnamer didn't solve the problem. Will stay on version 3.0.1 for now.

**Comment by kMutagene** [comment]
fixed via https://github.com/plotly/Plotly.NET/commit/5cc014352359bd7e5befa4649761d55c2954003e, will be in the next release
