### ISSUE TITLE
Combining charts leads to tag duplication

### ISSUE THREAD

**Issue by bvenn** [plotly/Plotly.NET#374]
### Description

When combining charts using `Chart.combine` or `Chart.Grid`, `title`, `meta` and `link` tags in the html head are duplicated.

### Repro steps

Please provide the steps required to reproduce the problem

1. Generate combined chart
```fsharp
#r "nuget: Plotly.NET, 4.0.0"

open Plotly.NET

[
    Chart.Point([1,2])
    Chart.Point([1,2])
]
|> Chart.combine
|> Chart.show
```

3. Look at the html

![image](https://user-images.githubusercontent.com/28917670/224930122-b8d0eae8-6b37-4e33-93d6-174b2295ccd9.png)

**Comment by kMutagene** [comment]
For reference, it might be a bad idea to append head tags on combination at all. When a combined chart should have additional tags, they should be set after combination

**Comment by kMutagene** [comment]
fixed for the current default head tags. Might be worth to model mathjax reference the same way we currently model the plotly.js reference instead of adding it to additional head tags.
