### ISSUE TITLE
share X-axis in Chart.Stack

### ISSUE THREAD

**Issue by hoangdungt2** [plotly/Plotly.NET#38]
Hi again,
Really enjoy the package so far. I notice on the plotly documentation there is a section about share axis subplots:
https://plotly.com/python/subplots/ with the option of `shared_xaxes=True`, wonder how I can do the same in `FSharp.Plotly`, I played around with `Chart.withX_AxisStyle` and `Chart.withX_Axis` but didn't go anywhere. Do give some advice, thanks.

**Comment by kMutagene** [comment]
Hi there again,

I'm glad you like it! What you want to do is something that I think we definitely should offer. However looking into it I didn't get the subplot grid working directly. When I have a working prototype I will get back at you and publish a prerelease package so you can test it. Thanks for reporting what you are doing with our library, it's really interesting to see.

**Comment by hoangdungt2** [comment]
Thanks Kevin, I'm using FSharp.Plotly in several projects in my company, certainly looking forward to the new features.

**Comment by kMutagene** [comment]
Hi @hoangdungt2 , i implemented a new version of the chart, `Chart.SingleStack`, wich is a version of the also fresh Chart.Grid with only 1 column. Here is a snippet that should get you what you want for shared xAxis:

```
[
    Chart.Point([(0,1)]) |> Chart.withY_AxisStyle("This title")
    Chart.Point([(0,1)]) 
    |> Chart.withY_AxisStyle("Must be set",Zeroline=false)
    Chart.Point([(0,1)]) 
    |> Chart.withY_AxisStyle("on the respective charts",Zeroline=false)
]
|> Chart.SingleStack
|> Chart.withLayoutGridStyle(XSide=StyleParam.LayoutGridXSide.Bottom)
|> Chart.withTitle("Hi i am the new SingleStackChart")
|> Chart.withX_AxisStyle("im the shared xAxis")
|> Chart.Show
```

For more than one column, you can use `Chart.Grid`. Should be available as a new prerelease package [here](https://www.nuget.org/packages/FSharp.Plotly/1.2.3-beta2).

**Comment by hoangdungt2** [comment]
hi Kevin, 
Big thanks, the new nuget package works perfectly for me.
Really appreciate your quick action 👍👍
