### ISSUE TITLE
Axis styling not applied for 3D charts anymore

### ISSUE THREAD

**Issue by kMutagene** [plotly/Plotly.NET#381]
seems like somewhere in the plotly.js version increses, a fallback for `xaxis` and `yaxis` for `scene` objects has been lost, where the 3d plot would get the styles from the layout object sirectly when not set on `scene`.

This can be verified by comparing to using `withZAxisStyle`, as that function sets properties on the scene directly:

**Does not work:**

```fsharp
#r "nuget: Plotly.NET"
#r "nuget: Plotly.NET.Interactive"

open Plotly.NET
open Plotly.NET.LayoutObjects

Chart.Point3D([1,2,3])
|> Chart.withXAxis(LinearAxis.init(Title = Title.init(Text = "axis title")))
|> Chart.withYAxis(LinearAxis.init(Title = Title.init(Text = "axis title")))
|> Chart.withZAxis(LinearAxis.init(Title = Title.init(Text = "axis title")))
```

![image](https://user-images.githubusercontent.com/21338071/229766596-dc2978de-a520-4bbf-aa4e-44e46047454f.png)

**works:**

#r "nuget: Plotly.NET"
#r "nuget: Plotly.NET.Interactive"

open Plotly.NET
open Plotly.NET.LayoutObjects

let myScene = Scene.init(
    XAxis = LinearAxis.init(Title = Title.init(Text = "axis title")),
    YAxis = LinearAxis.init(Title = Title.init(Text = "axis title")),
    ZAxis = LinearAxis.init(Title = Title.init(Text = "axis title"))
)

Chart.Point3D([1,2,3])
|> Chart.withScene(myScene)

![image](https://user-images.githubusercontent.com/21338071/229766523-a3d9bd0a-07d9-4d61-a4be-3420d93bbf03.png)

**Comment by bvenn** [comment]
I assume the described effect is intended. It is explicitly stated in the [documentation](https://plotly.net/03_0_3d-scatter-plots.html#3D-point-chart) to set the styling via the scene object

**Comment by kMutagene** [comment]
Seems like i just forgot about it :D
