### ISSUE TITLE
Image rendering is low

### ISSUE THREAD

**Issue by kunjiangkun** [plotly/Plotly.NET#383]
In the image rendering function. a new brower is always lauched. This is not efficient and time consuming if you need to render many images. Is it possible to use a static instance of the browser instead of launch new one every time?

```
member this.RenderSVGAsync(width: int, height: int, gChart: GenericChart.GenericChart) =
            task {
                use! browser = fetchAndLaunchBrowserAsync ()

                let! renderedString =
                    tryRenderAsync browser width height StyleParam.ImageFormat.SVG (gChart |> toFullScreenHtml)

                return renderedString |> fun svg -> System.Uri.UnescapeDataString(svg) |> skipDataTypeString
            }
```

**Comment by kMutagene** [comment]
Well first, the download should only happen once, after which the downloaded instance is used during the rest of the runtime.

However, you absolutely can point to a local instance of chromium via setting `PuppeteerSharpRendererOptions.localBrowserExecutablePath`

**Comment by kMutagene** [comment]
closing this for now since the appropriate setting is there. Feel free to reopen when there are more issues with setting the browser path.
