### ISSUE TITLE
freebsd not supported altough dotnet runs fine.

### ISSUE THREAD

**Issue by devosalain** [plotly/Plotly.NET#384]
Unhandled exception. System.InvalidOperationException: Not supported OS platform

**Comment by kMutagene** [comment]
Hi @devosalain, please include a reproducible code snippet that throws the exception, without any context it is hard to help here.

**Comment by kMutagene** [comment]
However i'd suspect that freebsd is not captured by the match cases here:

https://github.com/plotly/Plotly.NET/blob/2f94e879d23b0bdd259ec76cff99ae8946b375b2/src/Plotly.NET/InternalUtils.fs#L93-L105

So we'd need a default open command for `OSPlatform.FreeBSD`, what would the default be here? [open](https://man.freebsd.org/cgi/man.cgi?query=open&apropos=0&sektion=0&manpath=FreeBSD%208.2-RELEASE&format=html) ?

**Comment by kMutagene** [comment]
closing this in favor of tracking it via #397. @devosalain if you'd care to give feedback there it would be greatly appreciated.
