### ISSUE TITLE
[Documentation] Add SymbolStyle documentation

### ISSUE THREAD

**Issue by bvenn** [plotly/Plotly.NET#385]
### Description

It's not trivial to set the marker symbols to be open circles. This could be documented.

```fsharp
Chart.Point([1,2],MarkerSymbol = MarkerSymbol.Modified(MarkerSymbol.Circle,SymbolStyle.Open)) 
```

![image](https://user-images.githubusercontent.com/28917670/234223349-cfa5f891-9989-4c8d-8b1c-8a46be4bd828.png)

**Comment by kMutagene** [comment]
done: https://plotly.net/general/styling-markers.html
