### ISSUE TITLE
Compile error while building a C# proyect with Plotly.NET library using C# binding

### ISSUE THREAD

**Issue by ivanjimenez** [plotly/Plotly.NET#390]
### Description

Can't build a simple code for Plotly.NET C# Binding in a rage plot graph:

https://plotly.net/02_3_range-plots.html

I am trying to translate F# code to C#

![image](https://github.com/plotly/Plotly.NET/assets/908544/9d9756cd-f02a-40b3-8008-b503ea5e6805)

### Repro steps

1. I am trying to make a Range Graph with code provided in F# translated to C#:

```C#
...
using Plotly.NET.CSharp;
using Microsoft.Web.WebView2;
using Microsoft.Web.WebView2.WinForms;
using Plotly.NET.TraceObjects;
using Plotly.NET;
...

        Plotly.NET.Chart2D.Chart.Range(
             x: new double[] { 1, 2 },
             y: new double[] { 5, 10 },
             upper: X,
             lower: Y,
             mode: StyleParam.Mode.Lines_Markers,
            MarkerColor: System.Drawing.Color.FromName("Blue"),
            RangeColor : System.Drawing.Color.FromName("Red")

         )
         .WithTraceInfo("Hello from C#", ShowLegend: true)
         .WithXAxisStyle<double, double, string, double>(Title: Plotly.NET.Title.init("xAxis"))
         .WithYAxisStyle<double, double, string, double>(Title: Plotly.NET.Title.init("yAxis"))
         .SaveHtml(strPath);
```
2. There is an error in IDE

![image](https://github.com/plotly/Plotly.NET/assets/908544/eef3ffbb-74f6-4bb8-a0ca-b3834e2ed456)

### Expected behavior

With other charts this library works

### Actual behavior

Maybe there is an error in the argument, but with no documentation for API in C# it results tricky. 

### Known workarounds

Unknown

### Related information 

* Operating system: Windows 10
* Branch: version 4.1.0
* .NET Runtime, CoreCLR or Mono Version: .net 7.0
* Performance information, links to performance testing scripts: no scripts

**Comment by kMutagene** [comment]
Your issue is three-fold:

1. This is not an error, it is how C# wants you to annotate Generics: in the case of the method you are using, you must annotate 7 Generics. In F# you do not have to do that, and this is the main reason why the C# bindings even exist, instead of further optimizing the F# API to be directly consumed from C#.

2. The `Color` type must be Plotly.NET.Color.

2. While you reference `Plotly.NET.CSharp`, you are not using the Chart method from it. I'd suggest not opening the `Plotly.NET` root namespace at all if you want to use native C# bindings to avoid confusion (many things are named the same naturally).

    While the sample documentation is not ported, the API reference of `Plotly.NET.CSharp` is documented extensively. Here is the section on `Chart.Range`: https://plotly.net/reference/plotly-net-csharp-chart.html#Range
    
    Here is a working example:

    ![image](https://github.com/plotly/Plotly.NET/assets/21338071/243848c3-ab6d-4968-952c-afb48d3d6530)

    Note that you have to annotate less (3) Generics with the actual C# binding, and they have helpful names:

    ![image](https://github.com/plotly/Plotly.NET/assets/21338071/ad81360e-3a71-4d1d-83ae-52fbb8d60462)

**Comment by ivanjimenez** [comment]
Hi, 

Thanks for your explanations. I will follow your indications. Although Plotly C# Api is well documented, I think is a little messy and there are not many examples of using it. You must convert a lot of F# examples in C#. F# is not complicated, but I miss more resources about fantastic plotly .net c# library.

Thanks a bunch!
