### ISSUE TITLE
Increase verbosity of Markdown comments for hoverinfo of Chart functions

### ISSUE THREAD

**Issue by kMutagene** [plotly/Plotly.NET#40]
It seems like due to the Chart creating functions being static members of a class with optional arguments, the single parameters cannot be documented via markdown comments. Therefore, i would suggest we add a verbose description to the member itself that lists the key information about each argument for the chart.

**Comment by kMutagene** [comment]
As xml doc support for F# has improved and the docs auto generate content from this type of inline docs, a switch to xml documentation seems ideal.

**Comment by kMutagene** [comment]
It is now especially usefull to use xml documentation, as it will greatly improve the API documentation

**Comment by dsyme** [comment]
This is great - yes, for now all F# libraries should be using XML
