### ISSUE TITLE
Plotly.Net.csharp targeting

### ISSUE THREAD

**Issue by MosGeo** [plotly/Plotly.NET#402]
### Description

The CSharp extension package targets dotnet 6 while main package targets dotnet standard. Is this decision made for technical reasons?

### Rational
I am trying to use Plotly.Net.csharp inside unity engine  (through a webview) which still doesn't support .NET 6.

**Comment by kMutagene** [comment]
> Is this decision made for technical reasons?

`Optional<T>` is a record struct, so we need C# 10 which is only available for .net 6+: 
https://github.com/plotly/Plotly.NET/blob/e69b2ec8eab5bd8f182ddfbcb9126455aca2a891/src/Plotly.NET.CSharp/Optional.cs#L7-L23

**Comment by kMutagene** [comment]
You could however use the core F# API from C#, which is netstandard2.0
