### ISSUE TITLE
Saving static images

### ISSUE THREAD

**Issue by asdsad345433543rew** [plotly/Plotly.NET#403]
### Description

Chart.SaveJPG
Chart.SavePNG
Chart.SaveSVG

None of these works, the application freezes

### Repro steps

Please provide the steps required to reproduce the problem

Console c# application
Plotly.NET
Plotly.NET.CSharp
Plotly.NET.ImageExport

### Expected behavior

These methods should produce an image

### Actual behavior

Application freezes

### Known workarounds

Please provide a description of any known workarounds.

### Related information 

Windows 10
NET 6

**Comment by kMutagene** [comment]
Do you have an internet connection while running the console app? It will download the chromium browser for rendering purposes, so that might take a while (or never finish) depending on your internet connection

**Comment by kMutagene** [comment]
@asdsad345433543rew Also, if you could provide a minimum reproducible example application, I could have a look. All i can currently say is that it works for me on a .NET 6 C# console application with this minimal example:

```csharp
using Plotly.NET.CSharp;
using Plotly.NET.ImageExport;

var fig =
    Chart.Point<int, int, string>(
        x: new[] { 1, 2, 3, 4 },
        y: new[] { 10, 15, 13, 17 }
    );

fig.SaveJPG("C:\\Users\\_____\\Source\\repos\\testchart.jpg");
```

**Comment by asdsad345433543rew** [comment]
It seems it was a problem with the chromium download, I delete all generated folders (bin, obj), rebuild the solution and now its working.
Thank you I'm closing this thread.
