### ISSUE TITLE
Enable GitHub Discussions

### ISSUE THREAD

**Issue by dcuccia** [plotly/Plotly.NET#411]
Hi, just a suggestion - as someone new to the project, I'm hesitant to create an "Issue" for something where I may just be doing it wrong.  It might be advantageous to collect suggestions/ideas/questions from the community through enabling GitHub "Discussions", instead of inviting others to create Issues directly. Then, following a discussion, an Issue can be created that is concise and appropriate.

For example, I'm currently trying to figure out if there is an elegant way to update the `LinearAxis.ScaleAnchor` property using the fluent C# bindings (trying to get the equivalent of "axis equal" in Matlab for plotting heat maps).  I _think_ there needs to be an additional `ScaleAnchor` parameter in the `.WithXAxis` and `.WithYAxis` extension methods, and I'm happy to submit a PR for that, but I probably don't see the bigger picture on design features/roadmap/etc.

**Comment by kMutagene** [comment]
I usually encourage people to join the fslab discord server (linked in the [readme](https://github.com/plotly/Plotly.NET#readme)) for these kind of questions. However, I have been a bit torn on this lately - discord has very low friction, but is hard to search and is not indexed by search engines. However, enabling discussions here adds yet another layer, as we will not close the server in favor of discussions. See also https://github.com/plotly/Plotly.NET/issues/407#issuecomment-1657763525. 

I'll enable the Discussion feature and see where things will evolve. Thanks for the input.

**Comment by dcuccia** [comment]
Thanks for the feedback and sorry I missed the readme suggestion. Shall I post the issue above as a trial balloon for Discussions, or solicit feedback first on the discord server?

**Comment by kMutagene** [comment]
> sorry I missed the readme suggestion

no worries, I meant that more as a "you can find the link there if you are interested"

> Shall I post the issue above as a trial balloon for Discussions

I think that would be cool, Ideally under the Q&A section 👍

**Comment by kMutagene** [comment]
I'll close this, @dcuccia feel free to open discussions at any time.
