### ISSUE TITLE
Option to set DPI for static image export

### ISSUE THREAD

**Issue by nhirschey** [plotly/Plotly.NET#416]
### Description

I want to use `Chart.savePNG` to save plots so that I can include them in latex documents. The default 600x600 size results in blurry images, so I need to increase the dots per inch (dpi). But when I increase size using `Chart.savePNG(height=1000,width=1000)`, the text and markers look too small because their size is still the same number of pixels. As a result, I have to manually change image size, marker size, and text size whenever I want to increase resolution.

It would be nice if a dpi option increased resolution while keeping apparent marker, text, etc. size constant.

### Repro steps

Please provide the steps required to reproduce the problem

```fsharp
let exampleChart =
    Chart.Point([ 1.; 2.; 2.; 4.; 5. ], [ 1.; 2.; 2.; 4.; 5. ])

// blurry
exampleChart
|> Chart.savePNG ("blurry", Width = 300, Height = 300)

// Clear but text and markers appear much smaller
exampleChart
|> Chart.savePNG ("clear-but-small", Width = 900, Height = 900)
```

### Expected behavior

I'd like the "clear-but-small" image to be the same proportions as "blurry", just clearer due to higher dpi.

See for example dpi options for [ggsave](https://ggplot2.tidyverse.org/reference/ggsave.html) in R.

**Comment by kMutagene** [comment]
I have done some digging in the docs of the function that is used in the browser to generate these images, and it sadly seems like there is no direct option for this. Other rendering engines for plotly.py support a `scale` parameter, but that does not seem to be an option for [`plotly.toImage`](https://plotly.com/javascript/plotlyjs-function-reference/#plotlytoimage), which is used in the PuppeteerSharpRenderer.

This thread goes a bit into details on a workaround: https://github.com/plotly/dash-core-components/issues/403#issuecomment-1119830795 . It involves using the `ToImageButtons`, which can be used on a plot displayed in the browser to offer a button to download a plot as image. On that button, you can set the scale (see [here](https://plotly.net/reference/plotly-net-configobjects-toimagebuttonoptions.html)). 

However, this is a manual process and therefore no real solution for static image export. I'd suggest going the route of the issue i mentioned - exporting to svg and using another program to export the svg to a correctly scaled image format (this is also how i usually make figures publication-ready).

**Comment by nhirschey** [comment]
I see, thank you for the svg tip @kMutagene, I understand now why your [publication example charts](https://github.com/plotly/Plotly.NET/tree/dev/publication/example_charts) use svg. Time to learn inkscape...

**Comment by pirrmann** [comment]
There is a `scale` parameter in `Plotly.toImage` in the PuppeteerSharpRenderer here. https://github.com/plotly/Plotly.NET/blob/11456b42a8875d3ddc6142e2f02129de229e5320/src/Plotly.NET.ImageExport/PuppeteerSharpRenderer.fs#L55

It's just that we don't allow it to surface in the API, but I don't see what would prevent us from doing that...

**Comment by kMutagene** [comment]
> There is a scale parameter in Plotly.toImage in the PuppeteerSharpRenderer here

Hmm weird, that parameter is not documented on the [plotly.js function reference](https://plotly.com/javascript/static-image-export/). Anyways, i'll try it and check whether it has the expected results.

**Comment by pirrmann** [comment]
> Hmm weird, that parameter is not documented on the [plotly.js function reference](https://plotly.com/javascript/static-image-export/). Anyways, i'll try it and check whether it has the expected results.

This had an effect back when I first contributed to Plotly.NET :) https://github.com/plotly/Plotly.NET/pull/179

**Comment by kMutagene** [comment]
Just played around and can confirm that scale works (kinda). The image has a larger size with the same DPI (instead of increasing the dpi on the same size), so i guess increasing the scale and then downsizing the image should have the intended effect right?

Still, very weird to not document this at the js docs. I'll prepare an update to the whole render engine thing soon.

**Comment by kMutagene** [comment]
would this achieve what you need @nhirschey ?

**Comment by kMutagene** [comment]
closing this, it will be available with the next major version release
