### ISSUE TITLE
Pareto Chart

### ISSUE THREAD

**Issue by kMutagene** [plotly/Plotly.NET#423]
### Description

> A Pareto chart is a type of chart that contains both [bars](https://en.wikipedia.org/wiki/Bar_chart) and a [line graph](https://en.wikipedia.org/wiki/Line_chart), where individual values are represented in descending order by bars, and the cumulative total is represented by the line. The chart is named for the [Pareto principle](https://en.wikipedia.org/wiki/Pareto_principle), which, in turn, derives its name from [Vilfredo Pareto](https://en.wikipedia.org/wiki/Vilfredo_Pareto), a noted Italian economist. [1]

**Example:**

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Pareto.PNG/768px-Pareto.PNG" width="50%" />

### Pointers

- Ideally, you start prototyping in a scripting or notebook environment where you can iterate fast. installation instructions can be found here: https://plotly.net/#Installation 
- Charts like this that are using baseline trace types to create a new chart type should only be implemented in the top-level [Chart API](https://github.com/plotly/Plotly.NET/tree/dev/src/Plotly.NET/ChartAPI). An example where this is already done is the [Range chart](https://github.com/plotly/Plotly.NET/blob/11456b42a8875d3ddc6142e2f02129de229e5320/src/Plotly.NET/ChartAPI/Chart2D.fs#L1276) that combines a set of differently styled line charts.
- When possible, use `#IConvertible` for data input, as this allows for `string`s, number types such as `int` and `float`, and `DateTime`.

### References

- [1] https://en.wikipedia.org/wiki/Pareto_chart

**Comment by rockfaith75** [comment]
I'm working on this

**Comment by kMutagene** [comment]
hey @rockfaith75 i think you worked on this together with @smoothdeveloper. Is one of you still planning to finish this? If not, I would greatly appreciate if you could link what you ended up with during the hackathon (e.g. a script or notebook you worked in) so others can use it as a foundation to tackle this chart. If also do not have anything to link, no worries, please just tell me that this issue is up-for-grabs again. Thanks ❤️

**Comment by rockfaith75** [comment]
Thanks Super😍Kevin!!!

The project is working with random data, I've just come back home to Italy from the beautiful Berlin and in the next days Gautier is calling me via zoom to clean up and test so we can commit, is it ok?
Could you please give me your number just in case?
Mine is +393493823145 - John Casagranda

Thank You Kevin for the great and crucial support during the awesome F# for Data Science Conference at Novotel, congratulations once again to the Team!

Come to visit me in Italy whenever you want, welcome anytime, R'n'R!!!
🎸💜💫

John JC Casagranda

**Comment by kMutagene** [comment]
Hey @rockfaith75 cool that you are still working on this, take all the time you need. 

I might be best reachable on the fslab discord server: https://discord.gg/k3kUtFY8DB

**Comment by smoothdeveloper** [comment]
@kMutagene this is what we ended up playing with during the hackaton, in meantime it is useful to people lurking.

```fsharp

#r "nuget: Plotly.NET"
open Plotly.NET
open Plotly.NET.TraceObjects

let labelAndValues = [
    
    "Child Care"      , 44.8 
    "Public Transport", 27.2 
    "weather"         , 19.6
    "Traffic"         , 56.
]

module Seq =
    let unzip keyValues =
        keyValues |> Seq.map fst
        , keyValues |> Seq.map snd

type Chart with
    static member Pareto(keysValues: seq<string * float>, ?Name: string, ?Label: string) =
        let orderedLabels, orderedValues =
            keysValues
            |> Seq.sortByDescending snd
            |> Seq.unzip
        
        let sum = orderedValues |> Seq.sum
        let topPaddingRatio = 0.05
        let cumulativeSum = 
            Seq.scan (+) 0. orderedValues
             |> Seq.skip 1
        
        let paretoValues = 
            Seq.zip orderedLabels cumulativeSum
            |> Seq.map (fun (label,value) -> label, value / sum * 100.) 
        
        let bars = Chart.Column(Seq.zip orderedLabels orderedValues,?Name=Name)
        
        let points = 
            Chart.Point(
                paretoValues
                , ShowLegend = false
                , Marker     = Marker.init(Size = 8, Color = Color.fromKeyword Black, Symbol = StyleParam.MarkerSymbol.Cross, Angle = 45.)
            )
            |> Chart.withAxisAnchor (Y = 2)
            
        let lines = 
            Chart.Line(
                paretoValues
                , Name       = "Cumulative %"
                , ShowLegend = true
            ) 
            |> Chart.withAxisAnchor (Y = 2)
            
        [bars;lines;points] 
        |> Chart.combine 
        |> Chart.withYAxisStyle (
                ?TitleText = Label
                , Id       = StyleParam.SubPlotId.YAxis 1
                , ShowGrid = false
                , MinMax   = (0.,sum * (1.+topPaddingRatio))
            )
        |> Chart.withYAxisStyle (
                TitleText    = "%"
                , Side       = StyleParam.Side.Right
                , Id         = StyleParam.SubPlotId.YAxis 2
                , MinMax     = (0.,100. * (1.+topPaddingRatio))
                , Overlaying = StyleParam.LinearAxisId.Y 1
            )


Chart.Pareto(labelAndValues, Name="Budget", Label="$") |> Chart.show
```

I intend to work with @rockfaith75 in order to make a full fledged PR that will meet the bar for integration in the library.

**Comment by kMutagene** [comment]
This has been merged 🥳 , thank you @smoothdeveloper and @rockfaith75 !
