### ISSUE TITLE
LinearAxis CategoryOrder not working as expected

### ISSUE THREAD

**Issue by kunjiangkun** [plotly/Plotly.NET#450]
### Description

Setting CategoryOrder seems has no effect when there are multiple categories: 
xAxis.SetValue("categoryorder", "category ascending");

* Operating system
* Branch
* .NET Framework 4.8
* plotly.js : 2.30.1

**Comment by kMutagene** [comment]
Hey @kunjiangkun can you please attach a code snippet that reproduces the issue? Otherwise it is hard to pin down such issues

**Comment by kunjiangkun** [comment]
var xAxis = LinearAxis.init<IConvertible, IConvertible, IConvertible, IConvertible, IConvertible, IConvertible>(
    Title: xTitle, ZeroLine: false, AutoMargin: TickAutoMargin.All);
xAxis.SetValue("categoryorder", "category ascending");

// Scatter Combined
var scatterCombined = (scatterList.Any() ? Chart.Combine(scatterList) : Chart.Invisible())
    .WithUpdateMenu(LineStyleMenu)
    .WithTitle(chartTitle, TitleFont: Font.init(Size: titleFontSize))
    .WithXAxis(xAxis)
    .WithLayout(plotLayout)
    .WithSize(plotWidth, plotHeight);

**Comment by kMutagene** [comment]
Sorry but without the actual data that is in those plots it is still not possible for me to help here

**Comment by kMutagene** [comment]
closed until further feedback
