### ISSUE TITLE
Implement scaleratio and scaleanchor

### ISSUE THREAD

**Issue by egreglee** [plotly/Plotly.NET#47]
### Description

I'm using ```FSharp.Plotly``` on 2-d map data using ```Chart.Line``` and ```Chart.Point``` with ```Chart.Combine```.  This works well except that the x- and y-axis scales are different, so distances in the two directions are inconsistent and squares map to rectangles.  As far as I can tell, this is addressed by ```scaleratio``` and ```scaleanchor``` in base plotly, but these are not exposed here.  Is it possible to add this?

**Comment by kMutagene** [comment]
hi @egreglee ,

thanks for reporting this. In general, you can set any kind of property by adding named properties to the underlying dynamic object of our types. This can however be very tedious when you are working with nested objects. Could you provide a small example the plot that you generate using this library so i can check where this property can be set and maybe give it a quick typesafe implementation?  

scaleratio and scaleanchor seem to be properties of the Axes of a plot, so you can set the property on an empty axis object like this:

```F#
let myAxis = Axis.LinearAxis.init()
myAxis?scaleratio   <- 1
myAxis?scaleanchor  <-"y1"
```

However i agree that this property should be included in the axis constructor in a typesafe manner.

**Comment by egreglee** [comment]
Thank you for the prompt response. Here is the code:

``` let chart (tag: string) (roads: OdrXml.Road[]) = 
    let planViewPoints = List.ofArray roads |> 
                         List.map (fun (r: OdrXml.Road) -> (r.Name, Odr.Xml.planViewPoints r))
    let lines =  List.map (fun (pt: (Option<string> * WorldCoordinates list)) -> 
                            let rname = match fst pt with
                                        | Some string -> string
                                        | None -> "Road ???"
                            Chart.Line([for wc in (snd pt) -> (wc.X, wc.Y)],
                              Name=rname,
                              Color="lightgray", Showlegend=false)) planViewPoints
    
    let waypoints = Odr.Xml.curvatureWaypoints roads
    let points = List.map (fun pt ->
                            let rname = match pt.Road.Name with
                                        | Some string -> string
                                        | None -> "Road ???"
                            let centerPoint = pt.CenterLane.CurvePoint
                            let speeds = rname + " " + speedSummary pt
                            Chart.Point([(centerPoint.X, centerPoint.Y)],
                                        Name=speeds, Showlegend=false))
                           (List.ofArray waypoints)
   
    List.append lines points |> Chart.Combine |> Chart.withTitle(tag) 
      |> Chart.withSize(1000.0, 1000.0)
      |> Chart.withLayout(Layout.init (Hovermode=StyleParam.Hovermode.Closest))```

How would I set the Axis properties here? Using ```Chart.withX_Axis```?

**Comment by kMutagene** [comment]
Hi @egreglee ,
After testing the scaleratio and scaleanchor properties, they do not seem to do what you want to achieve, at least not completely. Here is a small example where i set the properties:

```F#

let points = [for i in 0 .. 10 do (i,i)] |> Chart.Point
let line = [for i in 0 .. 10 do (i,i*2)] |> Chart.Line

let myXAxis = 
    let tmp = Axis.LinearAxis.init()
    tmp?scaleratio   <- 1
    tmp?scaleanchor  <-"x"
    tmp

let myYAxis = 
    let tmp = Axis.LinearAxis.init()
    tmp?scaleratio   <- 1
    tmp?scaleanchor  <-"x"
    tmp

[
    points
    line
]
|> Chart.Combine
|> Chart.withX_Axis (myXAxis,1)
|> Chart.withY_Axis (myYAxis,1)
|> Chart.Show

```

Note that you now can only _zoom in and out_ of the genereated chart with a fixed ratio:

![image](https://user-images.githubusercontent.com/21338071/88627286-5f4c2700-d0ac-11ea-9668-ccb903873cb9.png)


If i understand your problem correctly, your already have 'wrong' (not 1:1) ratios of the axis ranges to start with (Just as in my example). You can simply set the ranges yourself using the `withX_AxisStyle` and  `withY_AxisStyle` functions by setting `MinMax` to the same range for both axes:


```F#
[
    points
    line
]
|> Chart.Combine
|> Chart.withX_Axis (myXAxis,1)
|> Chart.withY_Axis (myYAxis,1)
|> Chart.withX_AxisStyle("Some Title",MinMax=(0.,20.))
|> Chart.withY_AxisStyle("Some Title",MinMax=(0.,20.))
|> Chart.Show
```

![image](https://user-images.githubusercontent.com/21338071/88627352-7be85f00-d0ac-11ea-9f75-78e3a55e6e81.png)
That way you get 1:1 ratio axes and also cant destroy the 1:1 ratio by zooming in and out. I hope this is of help for you.

**Comment by egreglee** [comment]
I think ```scaleratio``` and``` scaleanchor``` do exactly what it is needed in this application:  force the data-space to screen-coordinate scaling to be the same for x and y.  Thus if a one unit change in the x data  produces an n-pixel change in screen coordinates, then a one-unit change in the y data will also produce an n-pixel change in screen coordinates.  In your example, the point trace lies along a 45° line on the screen, which is what a map requires.

That seems to be the intent of these two properties: [Fixed-ratio axes](https://plotly.com/javascript/axes/#fixedratio-axes)

In your example, this is the minimal fragment:

```[points; line] |> Chart.Combine |> Chart.withY_Axis(myYAxis) |> Chart.Show;;;```

In words: "do whatever you want with the X axis, but use a Y axis whose data-to-screen conversion is the same as the X axis."

The workaround is good enough for me.  It would be nice to have a type-safe way to do this, but I don't know where that fits in your work.  It's up to you whether we close this issue now.

**Comment by kMutagene** [comment]
I see, when examining the first example of mine closer i can now see that both axes are indeed scaled equally. This is a very useful property and it seems pretty easy to add. I will leave this open and move it to the backlog so we don't forget about implementing it.

**Comment by kMutagene** [comment]
ScaleRatio and ScaleAnchor have been added to `LinearAxis`.

**Comment by egreglee** [comment]
Thank you for addressing this.
