### ISSUE TITLE
Apply consistent F# Style

### ISSUE THREAD

**Issue by bvenn** [plotly/Plotly.NET#55]
### Description

To ensure consistent F# style, the usage of underscores should be avoided (except for wildcards).

Examples:
- Chart.WithX_Axis
- Chart.WithX_AxisStyle
- ...

**Comment by dsyme** [comment]
Tbh exceptions can be made for this rule - eg the need for name disambiguation in a generated API may make underscores the best solution.

So don't feel like you have to be ultra strict on this

**Comment by WhiteBlackGoose** [comment]
Should it be closed then now?
