### ISSUE TITLE
Add example binder

### ISSUE THREAD

**Issue by kMutagene** [plotly/Plotly.NET#56]
Now that we have nice notebook formatter integration thanks to @WalternativE, i think we can try to put that feature more into focus, similar to what XPlot is doing. 

@Joott as you already have experience with binder, could you give some insights on how to do that, or are you interested in taking care of setting up an example binder for this repo?

**Comment by caroott** [comment]
I set up a small binder environment with an example notebook:
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/Joott/Plotly.NET/ExampleBinder)
The changes include a Dockerfile at the root of the repository and a folder with a nuget.config and the notebook in docsrc. This is based on the example [here](https://github.com/dotnet/interactive/tree/main/samples/my%20binder). If this is what you are looking for @kMutagene I can open a pullrequest.

**Comment by kMutagene** [comment]
Closing this due to https://github.com/plotly/Plotly.NET/commit/a166ba2bfa604c0f6de4d8c1ce8143fec50bbe7e
