### ISSUE TITLE
Documentation Site has mixed-content

### ISSUE THREAD

**Issue by TheAngryByrd** [plotly/Plotly.NET#57]
### Description

The documentation site has mixed-content, or better known as using http for fsdocs-default.css.  This causes the page to not load css properly on browsers that prevent mixed sources from loading.

### Repro steps

- Chrome should have this by default
- Navigate to https://plotly.github.io/Plotly.NET/
- Site doesn't look like it should

### Expected behavior

Should load css

### Actual behavior

Doesn't load css

### Known workarounds

Please provide a description of any known workarounds.

### Related information 

![Screen Shot 2021-01-19 at 1 16 48 PM](https://user-images.githubusercontent.com/1490044/105076087-a06c3500-5a58-11eb-8420-ae3af00d0d1a.png)
![Screen Shot 2021-01-19 at 1 16 41 PM](https://user-images.githubusercontent.com/1490044/105076089-a104cb80-5a58-11eb-9915-9d6998d02538.png)

**Comment by kMutagene** [comment]
Thanks for reporting that @TheAngryByrd, i missed that because i never tried to reach the page over https 🤦 ! I updated the docs and enforced https for the whole page now and it works at least for me now, can you confirm?

Thanks again!

**Comment by TheAngryByrd** [comment]
Looks great!
