### ISSUE TITLE
.Net Interactive don't render chart in workbook

### ISSUE THREAD

**Issue by maumai** [plotly/Plotly.NET#60]
### Description

Could be documentation or code issue. But according to the documentation ending the cell with the value of the chart should render it in the workbook.

### Repro steps

Running below cell in a .Net interactive workbook does not render the chart.

#r "nuget: Plotly.NET, 2.0.0-beta1"
#r "nuget: Plotly.NET.Interactive, 2.0.0-beta1"

open Plotly.NET
open Plotly.NET.Interactive

let xData = [0. .. 10.]
let yData = [0. .. 10.]

let mychart =
    Chart.Point(xData,yData)
    |> Chart.withX_AxisStyle ("xAxis", Showgrid=false)
    |> Chart.withY_AxisStyle ("yAxis", Showgrid=false)

mychart

### Expected behavior

Chart is rendered in the workbook

### Actual behavior

Running the cell results in 

Item1 | Item2 | Item3
-- | -- | --
Plotly.NET.Trace | Plotly.NET.Layout | Plotly.NET.Config

**Comment by kMutagene** [comment]
There was a bug in the 2.0.0-beta1 - beta3 packages that prevented the formatter to be automatically registered. As of beta5 which I just published, you should be able to render the charts in the cell output again:

```fsharp
#r "nuget: Plotly.NET, 2.0.0-beta5"
#r "nuget: Plotly.NET.Interactive, 2.0.0-beta5"
```

Please let me know if that works for you ;)

**Comment by maumai** [comment]
Thanks, :) It works nicely with the bet5 packages.
