### ISSUE TITLE
Shared axes in stacked charts show strange behaviour

### ISSUE THREAD

**Issue by bvenn** [plotly/Plotly.NET#62]
### Description

When using Chart.Grid or Chart.SingleStack the default axis option is `sharedAxes=false`, which in practice does not work. 
When explicitly setting sharedAxes=false, the resulting chart shows a strange bahaviour. Both axes appear at the lowest chart.

### Repro steps

```
#r "nuget: Plotly.NET, 2.0.0-beta5"
open Plotly.NET

let ch1 = Chart.Point([1,2])
let ch2 = Chart.Point([2,1])

Chart.SingleStack([ch1;ch2]) |> Chart.Show
Chart.SingleStack([ch1;ch2],true) |> Chart.Show
Chart.SingleStack([ch1;ch2],false) |> Chart.Show
```

### Expected behavior

Two stacked charts with a x-axis attached to each chart separately.

### Actual behavior

![image](https://user-images.githubusercontent.com/28917670/105991112-b2c32000-60a3-11eb-997f-9e2161e26899.png)

### Reference

https://github.com/plotly/Plotly.NET/blob/350b3b59b2fe0ca9afbd212a66c5106ce29f7c98/src/Plotly.NET/ChartExtensions.fs#L718

### Additional information

When multiple charts are combined using Chart.Grid, some are merged, some remain separate

```
[1 .. 10]
|> List.map (fun x-> Chart.Point([x,2*x],string x))
|> fun x ->  Chart.Grid ([x.[..5];x.[6..]],false)
|> Chart.Show 
```

![image](https://user-images.githubusercontent.com/28917670/105993661-f53a2c00-60a6-11eb-8aac-ec944a406e88.png)

**Comment by kMutagene** [comment]
To give this a little context, this definitely has its root in the way the subplot domains are calculated, especially for the case where the grid has not the same dimensions on every row:

https://github.com/plotly/Plotly.NET/blob/350b3b59b2fe0ca9afbd212a66c5106ce29f7c98/src/Plotly.NET/ChartExtensions.fs#L733-L748

Also related : #48

**Comment by kMutagene** [comment]
Should be fixed with the next release.
