### ISSUE TITLE
Versioning issues with 2.0.0-beta6

### ISSUE THREAD

**Issue by gusennan** [plotly/Plotly.NET#64]
Thanks for providing this, it looks awesome. I'm eager to try it out.

### Description

Cannot resolve dependencies with .NET core 5

### Repro steps

Create a notebook using F# and try to install Plotly.NET or the interactive

### Expected behavior

It installs without issue

### Actual behavior

It's unable to resolve dependencies. It looks like it's depending on packages that aren't yet publicly available on NUGET.

```
#r "nuget: Deedle, 2.3.0"
#r "nuget: Plotly.NET, 2.0.0-beta6"
#r "nuget: Plotly.NET.Interactive, 2.0.0-beta6"

open Deedle
```
prints 
```
/tmp/nuget/70087--17f2cd13-d092-48c7-a1f4-00e4a3b53f19/Project.fsproj : warning NU1603: Plotly.NET.Interactive 2.0.0-beta6 depends on Microsoft.DotNet.Interactive (>= 1.0.0-beta.20574.9) but Microsoft.DotNet.Interactive 1.0.0-beta.20574.9 was not found. An approximate best match of Microsoft.DotNet.Interactive 1.0.0-beta.21108.3 was resolved.
/tmp/nuget/70087--17f2cd13-d092-48c7-a1f4-00e4a3b53f19/Project.fsproj : warning NU1603: Plotly.NET.Interactive 2.0.0-beta6 depends on Microsoft.DotNet.Interactive.Formatting (>= 1.0.0-beta.20574.9) but Microsoft.DotNet.Interactive.Formatting 1.0.0-beta.20574.9 was not found. An approximate best match of Microsoft.DotNet.Interactive.Formatting 1.0.0-beta.21108.3 was resolved.
/tmp/nuget/70087--17f2cd13-d092-48c7-a1f4-00e4a3b53f19/Project.fsproj : warning NU1603: Plotly.NET.Interactive 2.0.0-beta6 depends on Microsoft.DotNet.Interactive.FSharp (>= 1.0.0-beta.20574.9) but Microsoft.DotNet.Interactive.FSharp 1.0.0-beta.20574.9 was not found. An approximate best match of Microsoft.DotNet.Interactive.FSharp 1.0.0-beta.21108.3 was resolved.
/tmp/nuget/70087--17f2cd13-d092-48c7-a1f4-00e4a3b53f19/Project.fsproj : error NU1102: Unable to find package System.CommandLine with version (>= 2.0.0-beta1.21072.2)
/tmp/nuget/70087--17f2cd13-d092-48c7-a1f4-00e4a3b53f19/Project.fsproj : error NU1102:   - Found 17 version(s) in nuget.org [ Nearest version: 2.0.0-beta1.20574.7 ]
/tmp/nuget/70087--17f2cd13-d092-48c7-a1f4-00e4a3b53f19/Project.fsproj : error NU1102: Unable to find package FSharp.Compiler.Service with version (>= 39.0.3-preview.21102.10)
/tmp/nuget/70087--17f2cd13-d092-48c7-a1f4-00e4a3b53f19/Project.fsproj : error NU1102:   - Found 161 version(s) in nuget.org [ Nearest version: 39.0.0 ]
/tmp/nuget/70087--17f2cd13-d092-48c7-a1f4-00e4a3b53f19/Project.fsproj : warning NU1605: Detected package downgrade: FSharp.Core from 5.0.2-beta.21102.10 to 5.0.0. Reference the package directly from the project to select a different version. 
/tmp/nuget/70087--17f2cd13-d092-48c7-a1f4-00e4a3b53f19/Project.fsproj : warning NU1605:  Project -> Plotly.NET.Interactive 2.0.0-beta6 -> Microsoft.DotNet.Interactive.FSharp 1.0.0-beta.21108.3 -> FSharp.Core (>= 5.0.2-beta.21102.10) 
/tmp/nuget/70087--17f2cd13-d092-48c7-a1f4-00e4a3b53f19/Project.fsproj : warning NU1605:  Project -> Plotly.NET.Interactive 2.0.0-beta6 -> FSharp.Core (>= 5.0.0)
```

### Known workarounds

Tried downgrading to an earlier release, but they look like they're pinned to specific versions of .NET interactive

If I manually add the System.CommandLine and FSharpCompilerServices packages, even though they don't match the package specs, they seem to work:

```
#r "nuget: Deedle, 2.3.0"
#r "nuget: Plotly.NET, 2.0.0-beta6"
#r "nuget: Plotly.NET.Interactive, 2.0.0-beta6"
#r "nuget: System.CommandLine, 2.0.0-beta1.20574.7"
#r "nuget: FSharp.Compiler.Service, 39.0.0"
```

### Related information 

* Fedora 33
* .NET Core 5.0.103 [/usr/share/dotnet/sdk]

**Comment by kMutagene** [comment]
That's strange, as from my understanding you should have access to these packages from the notebook environment. 

it works for me both locally on a blank new notebook via VSCode and online in the binder environments spun up for the docs of this repository. 

How do you create and work on your notebook, also via the VSCode extension?

One thing i can try is to update the dependencies of the Interactive package to one of the Dotnet.Interactive preview versions that are publicly available on nuget, e.g. 1.0.0-beta.21152.4, i will let you know when that is done. So far, if you just want to play with the library, you can always use one of the binder links from the docs ;).

**Comment by gusennan** [comment]
Hey, thanks for getting back to me!

To create the notebook I use Anaconda's Jupyter Lab with the F# kernel. I follow the instructions here:

https://github.com/dotnet/interactive/blob/main/docs/NotebooksLocalExperience.md

I do not use VSCode. Maybe the issue is because VSCode with notebooks is on a preview/insiders channel?

**Comment by kMutagene** [comment]
Hi @gusennan i dropped version 2.0.0-beta7 today, which should simplify the dependencies of the Interactive package. Can you give it a spin and tell me if it works for you now?

**Comment by kMutagene** [comment]
related: #67

**Comment by gusennan** [comment]
Sorry I haven't looked at this yet, I hope to get to it soon.
