### ISSUE TITLE
Do you have a chat for users and contributors?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [plotly/Plotly.NET#75]
Hello.

I think you're working on a great project. But a great project is also about community. Do you have a dedicated chat for it?

If not, I highly recommend creating one in Discord. If anything, it's the first place where I (and many others) would go if wanted to use or help the project. (if needed, I can set it up).

**Comment by WhiteBlackGoose** [comment]
@kMutagene what do you think?

**Comment by kMutagene** [comment]
@WhiteBlackGoose you are definitely right about that. What do you think of Gitter? I think it has a strong advantage in that the public chat is indexed by search engines and it is nicely integrated with github. Discord always feels kind of overkill for these kinds of communities for me and it is also quite separated from the GitHub world, but i might be wrong about that.

**Comment by WhiteBlackGoose** [comment]
I think Discord might be a better idea. Yes, Gitter has a great integration with GH. And yes, it is indexed by search engines. But in all other aspects, it's quite behind Discord. In a Discord server you would have so much cool functionality, like 
- multiple channels. Say, `for-contributors`, `general`, or even `offtopic` for fun discussions
- custom role management. E. g. `maintainer`, `contributor`, `admin`, `moderator`. Of course, as well as custom permission management
- like in gitter, you can set up logger for events in a repo (via webhooks)
- it will also bring you more attention. The number of users of gitter and discord are not comparable, so imho it might merely get you more contributors. I personally would be way more inclined to get involved in plotly if there was a chat in Discord (where, by the way, all other .NET chats are).
- And it's free, it's not that you lose something creating a Discord server.

But if you are sure that gitter is a better idea, then that's what I say: having a gitter chat is *still* better than not having a chat at all.
@kMutagene

**Comment by kMutagene** [comment]
> having a gitter chat is still better than not having a chat at all.

gotcha. It can't hurt to have a community-driven Discord server. So if you would be willing to set up a server and manage it that would be greatly appreciated!

**Comment by WhiteBlackGoose** [comment]
@kMutagene sure! I'll PR an invite link once it's ready (and make you an admin/owner if you wish).

**Comment by kMutagene** [comment]
@WhiteBlackGoose awesome, thanks!

**Comment by WhiteBlackGoose** [comment]
The link: https://discord.gg/6nju7mRQ9G
