### ISSUE TITLE
Multi-axis chart using with*_Axis rather than with*_AxisStyle

### ISSUE THREAD

**Issue by kentcb** [plotly/Plotly.NET#77]
### Description

The documentation provides [an example](https://plotly.net/1_0_axis-styling.html#Multiple-axes-on-the-same-side-of-the-chart) of a multi-axis chart using `withY_AxisStyle`. However, I need more control over the axes, so want to use `Axis.LinearAxis.init` and `withY_Axis`, but when I do the chart does not appear as expected.

### Repro steps

```F#
let x = [1.; 2.; 3.; 4.; 5.; 6.; 7.; 8.; 9.; 10.; ]
let y = [2.; 1.5; 5.; 1.5; 3.; 2.5; 2.5; 1.5; 3.5; 1.]
let y' = y |> List.map (fun y -> y * 2.) |> List.rev

let firstAxis =
    Axis.LinearAxis.init(
        Anchor = StyleParam.AxisAnchorId.Y 1,
        Title ="First"
    )
let secondAxis =
    Axis.LinearAxis.init(
        Anchor = StyleParam.AxisAnchorId.Y 2,
        Title ="Second",
        Overlaying = StyleParam.AxisAnchorId.Y 1,
        Side = StyleParam.Side.Right
    )
let firstChart =
    Chart.Line(x, y)
    |> Chart.withAxisAnchor(Y = 1)
let secondChart =
    Chart.Line(x, y')
    |> Chart.withAxisAnchor(Y = 2)

[
    firstChart
    secondChart
]
|> Chart.Combine
|> Chart.withY_Axis firstAxis
|> Chart.withY_Axis secondAxis
|> Chart.Show
```

### Expected behavior

(I created this image by using `withY_AxisStyle` - basically just the code from the example in the docs)

![image](https://user-images.githubusercontent.com/1901832/119468881-3824bb80-bd8a-11eb-8c9b-841fc2e9f21f.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/1901832/119469246-833ece80-bd8a-11eb-9888-ab2d05ae5c46.png)

### Known workarounds

None known.

### Related information 

* Operating system: Windows 10
* Branch: I'm using `2.0.0-beta9`
* .NET Runtime: .NET 5.0

**Comment by muehlhaus** [comment]
Hi @kentcb,
using the 'withY_Axis' you have to set the id of the axis in addition. 
This should work:
`
[
    firstChart
    secondChart
]
|> Chart.Combine
|> Chart.withY_Axis (firstAxis,Id=1)
|> Chart.withY_Axis (secondAxis,Id=2)
|> Chart.Show
`
I think the confusion is the 'Anchor = StyleParam.AxisAnchorId.Y 1' part. This is not strictly necessary in your example. It specifies the anchor of the axis.... I know it is a lot of anchoring, but this provides maximal flexibility. ;)

I hope that helps.

**Comment by kentcb** [comment]
That's great - thanks @muehlhaus !
