### ISSUE TITLE
Accept IConvertible in Annotation.init

### ISSUE THREAD

**Issue by kentcb** [plotly/Plotly.NET#78]
### Description

`Annotation.init` does not accept `IConvertible` for `X` and `Y` like other APIs.

### Repro steps

Try to use a `DateTime` as the `X` for `Annotation.init`, which works fine with other APIs like `Shape.init`.

### Expected behavior

Should be consistent.

### Actual behavior

Requires a `float`.

### Known workarounds

Converting to milliseconds since unix epoch and passing that in as a float.

### Related information 

* Windows 10
* `2.0.0-beta9`
* .NET 5

I noticed this problem does not seem unique to the .NET implementation: see [here](https://community.plotly.com/t/add-vline-with-annotation-and-datetime-as-x-axis/49732).

**Comment by kMutagene** [comment]
Good catch, i am on it right now ;)

**Comment by kMutagene** [comment]
Should be fixed in the next version:

```fsharp
let testAnnotation =
    Annotation.init(X=System.DateTime.Now, Y=0,Text="test")

Chart.Line([System.DateTime.Now, 5])
|> Chart.withAnnotations [testAnnotation]
|> Chart.Show
```

![image](https://user-images.githubusercontent.com/21338071/119775797-63abc100-bec4-11eb-82d3-4a2db9ad9196.png)

**Comment by kMutagene** [comment]
Should be fixed in the latest package. Please let me know if there are still problems

**Comment by kentcb** [comment]
Confirmed in preview release - thanks @kMutagene !!
