### ISSUE TITLE
Cannot name traces in a range chart?

### ISSUE THREAD

**Issue by kentcb** [plotly/Plotly.NET#79]
### Description

There doesn't appear to be a way to name traces in a `Chart.Range`.

### Repro steps

```F#
let rnd = System.Random()

let x  = [1.; 2.; 3.; 4.; 5.; 6.; 7.; 8.; 9.; 10.; ]
let y = [2.; 1.5; 5.; 1.5; 3.; 2.5; 2.5; 1.5; 3.5; 1.]

let yUpper = y |> List.map (fun v -> v + rnd.NextDouble())
let yLower = y |> List.map (fun v -> v - rnd.NextDouble())

let range1 =
    Chart.Range(
        x,y,yUpper,yLower,
        StyleParam.Mode.Lines_Markers,
        Color="grey",
        RangeColor="lightblue",
        Name = "Custom")

range1
|> Chart.Show

```

Results in:

![image](https://user-images.githubusercontent.com/1901832/119943611-9a71fc00-bfd6-11eb-9845-5d3613f7bfa2.png)

I cannot find any API to change "trace 0" and "trace 1" to something custom, but maybe I'm missing something obvious...?

### Expected behavior

An API should exist to customize the text shown for upper and lower bounds of the range.

### Actual behavior

Cannot find an API.

### Known workarounds

None known.

### Related information 

* Windows 10
* `2.0.0-beta9`
* .NET 5

**Comment by kMutagene** [comment]
cc @bvenn

**Comment by bvenn** [comment]
## Quickfix

For a quick fix, there is a possibility to update the individual traces in your MultiChart with names by hand:



```F#
#r "nuget: Plotly.NET, 2.0.0-beta9"
open Plotly.NET
open Plotly.NET.Trace

let rnd = System.Random()
let x  = [1.; 2.; 3.; 4.; 5.; 6.; 7.; 8.; 9.; 10.; ]
let y = [2.; 1.5; 5.; 1.5; 3.; 2.5; 2.5; 1.5; 3.5; 1.]
let yUpper = y |> List.map (fun v -> v + rnd.NextDouble())
let yLower = y |> List.map (fun v -> v - rnd.NextDouble())

let range1 =
    Chart.Range(
        x,y,yUpper,yLower,
        StyleParam.Mode.Lines_Markers,
        Color="grey",
        RangeColor="lightblue")

range1
|> GenericChart.mapiTrace (fun i trace -> 
    let traceName = 
        match i with
        | 0 -> "lower"
        | 1 -> "upper"
        | 2 -> "myData"
    trace
    |> TraceStyle.TraceInfo (Name=traceName)
    )
|> Chart.Show
```

![image](https://user-images.githubusercontent.com/28917670/119971300-12c5c680-bfb1-11eb-8450-c43bf0dd160f.png)

## Fix

The name for the lower and upper margins is not set here:
https://github.com/plotly/Plotly.NET/blob/3c03a1d96f129b901aae54ffe822c08e02b4e4f7/src/Plotly.NET/Chart.fs#L651

A solution could be to add additional optional parameter like `UpperName` and `LowerName` and assign these in lines 643 and 651 respectively. 

@kMutagene what do you think about it?

**Comment by kMutagene** [comment]
Yeah as this i a composite chart that always gets built the same way i agree that there should be optional arguments for passing these names, and also setting "upper" and "lower" (or maybe "upper/lower bound"?) as default trace names.

**Comment by kMutagene** [comment]
Should be fixed in the latest package. Please let me know if there are still problems

**Comment by kentcb** [comment]
Excellent! Thanks @bvenn and @kMutagene
