### ISSUE TITLE
Export Chart to SVG/PNG

### ISSUE THREAD

**Issue by LucasNmn** [plotly/Plotly.NET#90]
Hi,
is there an easy way to export a plotted chart directly from code as PNG or SVG?
I tried it using the ".toChartImage" function from the api but didn't find a working solution yet.

**Comment by kMutagene** [comment]
To export charts created with Plotly.NET directly as an image file, you need some kind of headless browser to do the javascript execution to render the chart first. There is a package out there using Pupeteer for that which might work for you, check #21 for that. However, there is an in-house solution by plotly which we still need to wrap for .NET use - It is on the roadmap but not quite here yet. 

Related/possible duplicates: #21 and #65.

**Comment by LucasNmn** [comment]
Thanks for your advice,
I will test that.

**Comment by kMutagene** [comment]
closed via #94. @LucasNmn if you have time and interest you might check out the docs for the new `Plotly.NET.ImageExport` package [here](https://plotly.net/0_1_image-export.html).

**Comment by LucasNmn** [comment]
I'm having problems getting the function to work in C#. SaveJPG seems to be unknown while I'm using Preview 6. But I already made my own workaround with Pupperteer as you mentioned in #21 and #65 .

**Comment by kMutagene** [comment]
Thanks for checking it out, i will test this in C# now to see if there's an issue. 

Just to be clear, `Plotly.NET.ImageExport` is a separate nuget package: https://www.nuget.org/packages/Plotly.NET.ImageExport/. Maybe i should add this to the docs. If you want access to `.SaveJP` you also have to open the `GenericChartExtensions` namespace. 

But if you have an approach that works for you already, thats just as fine.

**Comment by LucasNmn** [comment]
> Thanks for checking it out, i will test this in C# now to see if there's an issue.
> 
> Just to be clear, `Plotly.NET.ImageExport` is a separate nuget package: https://www.nuget.org/packages/Plotly.NET.ImageExport/. Maybe i should add this to the docs. If you want access to `.SaveJP` you also have to open the `GenericChartExtensions` namespace.
> 
> But if you have an approach that works for you already, thats just as fine.

Thanks for that. I thought it was inside the same package. X)
It's working now. But I have to fix authorization problems with my proxy.
